"use client";
import {useEffect,useRef,useState} from 'react';
import {Check,Copy,KeyRound,Link2,LoaderCircle,LogOut,Pencil,Plus,ShieldCheck,Trash2,UserRound} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Member,Profession,professionNames} from '@/lib/review-types';
import {Choice,professionOptions} from './review-controls';
import {AppearanceSettings} from './appearance';
import AccountSetup from './account-setup';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export function AccountDialog({open,onOpenChange,request,onChanged}:{open:boolean;onOpenChange:(v:boolean)=>void;request:Requester;onChanged:()=>Promise<void>}){
 const [setupToken,setSetupToken]=useState<string|null>(null);
 const [mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[profession,setProfession]=useState('internal'),[status,setStatus]=useState<{configured:boolean;emailReady:boolean;user:any}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),api=useRef(request);api.current=request;
 useEffect(()=>{if(!open)return;setError('');setMessage('');setPassword('');const account=new URLSearchParams(window.location.search).get('account');setSetupToken(account==='setup'?new URLSearchParams(window.location.hash.slice(1)).get('invite')||'':null);setMode(account==='recovery'?'password':'signin');if(account==='expired')setError('This link could not be completed. Sign in if your email is confirmed, or request a new password reset from this browser.');if(account==='confirmed')setMessage('Email confirmed. Your account is ready.');api.current('/api/auth').then(setStatus).catch(e=>setError(e.message));},[open]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await request('/api/auth',{method:'POST',body:JSON.stringify({action:mode,email,password,name,profession})});if(mode==='reset'){setMessage('If an account exists, its password reset link has been sent. Open it in this browser.');return}if(r.confirmation){setMessage('Check your email to confirm your account. Open the confirmation link in this browser, then sign in.');setMode('signin');setPassword('');return}setStatus(await request('/api/auth'));setPassword('');const url=new URL(window.location.href);url.searchParams.delete('account');window.history.replaceState(null,'',url);await onChanged();onOpenChange(false);toast.success(mode==='password'?'Password updated':'Signed in. Your workspace is saved to your account.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(open&&setupToken!==null)return <AccountSetup token={setupToken} request={request} onClose={()=>{setSetupToken(null);onOpenChange(false)}}/>;
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v)}}><DialogContent className="account-dialog"><DialogHeader><DialogTitle>{mode==='password'?'Choose a new password':'Account settings'}</DialogTitle><DialogDescription>{status?.user?'Your account and workspace preferences.':'Choose your appearance here. Sign in to access your projects from another device.'}</DialogDescription></DialogHeader>
 <AppearanceSettings/>
 {!status&&!error&&<LoaderCircle className="spin"/>}{status?.configured===false&&<div className="account-notice">Accounts are being connected. You can continue reviewing in the demo.</div>}
 {status?.configured&&!status?.emailReady&&!status?.user&&<div className="account-notice">Sign-in is connected. New account and reset emails are still being set up. You can continue with a review link.</div>}
 {status?.user&&mode!=='password'?<div className="account-summary"><span className="account-avatar"><UserRound size={26}/></span><strong>{status.user.name}</strong><p>{status.user.email}</p><span>{professionNames[status.user.profession as Profession]}</span><button className="button outline" disabled={busy} onClick={async()=>{setBusy(true);try{await request('/api/auth',{method:'POST',body:JSON.stringify({action:'signout'})});window.location.reload()}catch(e:any){setError(e.message);setBusy(false)}}}><LogOut size={16}/> Sign out on this device</button></div>:<>
 {['signin','signup'].includes(mode)&&<Tabs value={mode} onValueChange={v=>{setMode(v);setError('');setMessage('')}}><TabsList className="account-tabs"><TabsTrigger value="signin">Sign in</TabsTrigger><TabsTrigger value="signup">Create account</TabsTrigger></TabsList></Tabs>}
 <form onSubmit={submit} className="form-stack">{mode==='signup'&&<label>Your name<input autoComplete="name" required value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label>}{mode!=='password'&&<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='reset'&&<label>{mode==='password'?'New password':'Password'}<input type="password" minLength={8} maxLength={128} autoComplete={mode==='signin'?'current-password':'new-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='signup'&&<label>Your default role tag<Choice label="Your professional role" value={profession} onChange={setProfession} options={professionOptions}/></label>}
 {message&&<p className="account-message" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <button className="button primary full" disabled={busy||!status?.configured||(['signup','reset'].includes(mode)&&!status?.emailReady)}>{busy?<LoaderCircle className="spin" size={16}/>:<ShieldCheck size={16}/>} {mode==='signin'?'Sign in':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Save password'}</button>
 {mode==='signin'&&<button type="button" className="text-button" onClick={()=>{setMode('reset');setMessage('');setError('')}}>Forgot your password?</button>}{mode==='reset'&&<button type="button" className="text-button" onClick={()=>setMode('signin')}>Back to sign in</button>}
 </form></>}
 </DialogContent></Dialog>
}
export function PeopleDialog({open,onOpenChange,projectId,request,onChanged}:{open:boolean;onOpenChange:(v:boolean)=>void;projectId:string;request:Requester;onChanged:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[editing,setEditing]=useState<Member|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[profession,setProfession]=useState('internal'),[access,setAccess]=useState('editor'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[capabilities,setCapabilities]=useState({canManage:false,canManageAccounts:false,accountLinksReady:false}),[accountLink,setAccountLink]=useState<any>(null),api=useRef(request);api.current=request;
 async function refresh(){const r=await api.current('/api/members?project='+projectId);setMembers(r.members);setCapabilities(r)}
 useEffect(()=>{if(open){setError('');setAccountLink(null);refresh().catch(e=>setError(e.message))}},[open,projectId]);
 function reset(){setEditing(null);setName('');setEmail('');setProfession('internal');setAccess('editor')}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await request('/api/members',{method:'POST',body:JSON.stringify({projectId,id:editing?.id,name,email,profession,access})});await refresh();reset();onChanged();toast.success(editing?'Person updated':'Person added')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function generate(member:Member,purpose:'invite'|'recovery'){setBusy(true);setError('');setAccountLink(null);try{const result=await request('/api/account-links',{method:'POST',body:JSON.stringify({action:'generate',projectId,memberId:member.id,purpose})});setAccountLink({...result,name:member.name,memberId:member.id})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>!busy&&onOpenChange(v)}><DialogContent className="people-dialog"><DialogHeader><DialogTitle>Project people</DialogTitle><DialogDescription>Add a person and send their invitation link. They choose their own password. Role tags organize feedback; permissions control editing.</DialogDescription></DialogHeader>
 <div className="people-toolbar"><Choice label="Filter people by role" value={filter} onChange={setFilter} options={[{value:'all',label:'All roles'},...professionOptions]}/><button className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin+'/?project='+projectId);toast.success('Project sign-in link copied')}catch{toast.error('Could not copy the project link.')}}}><Copy size={15}/>Project sign-in link</button></div>
 {capabilities.canManage&&!capabilities.accountLinksReady&&<p className="account-notice">Invitations and password-reset links are awaiting activation of the server account connection.</p>}
 {accountLink&&<section className="account-link-result" aria-label="Account link"><strong>{accountLink.existing?'Sign-in link':accountLink.purpose==='recovery'?'Password reset link':'Invitation link'} · {accountLink.name}</strong><p>{accountLink.existing?accountLink.message:'Send this private link to '+accountLink.email+'. It works once and expires in 30 minutes. No email is sent automatically.'}</p><div><input aria-label="Link to send" readOnly value={accountLink.url} onFocus={e=>e.target.select()}/><button className="button primary" onClick={async()=>{try{await navigator.clipboard.writeText(accountLink.url);toast.success('Link copied')}catch{toast.error('Select and copy the link above.')}}}><Copy size={15}/>Copy link</button></div>{!accountLink.existing&&<button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await request('/api/account-links',{method:'POST',body:JSON.stringify({action:'revoke',projectId,memberId:accountLink.memberId})});setAccountLink(null);toast.success('Link revoked')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Revoke this link</button>}</section>}
 <div className="people-list">{members.filter(m=>filter==='all'||m.profession===filter).map(m=><div className="person-row" key={m.id}><span className="person-avatar">{m.name.slice(0,2).toUpperCase()}</span><div className="person-name"><strong>{m.name}</strong><span>{m.email||'Project administrator'}</span><small>{m.owner?'Administrator':m.joined?'Account connected':'Awaiting sign-in'} · {professionNames[m.profession]}{!m.owner&&' · '+(m.access==='editor'?'Can edit':'Comment only')}</small>
 {!m.owner&&capabilities.canManage&&<div className="person-account-actions"><button className="spec-link" disabled={busy||!capabilities.canManageAccounts} onClick={()=>void generate(m,'invite')}><Link2 size={13}/>Invite link</button><button className="spec-link" disabled={busy||!capabilities.canManageAccounts} onClick={()=>void generate(m,'recovery')}><KeyRound size={13}/>Reset password</button></div>}</div>
 {capabilities.canManage&&<><button className="icon-button" disabled={busy} aria-label={'Edit '+m.name} onClick={()=>{setEditing(m);setName(m.name);setEmail(m.email);setProfession(m.profession);setAccess(m.access)}}><Pencil size={15}/></button>{!m.owner&&<button className="icon-button" disabled={busy} aria-label={'Remove '+m.name+' from project'} onClick={async()=>{setBusy(true);try{await request('/api/members',{method:'POST',body:JSON.stringify({action:'remove',id:m.id,projectId})});setAccountLink(null);await refresh();onChanged();toast.success('Project access removed')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><Trash2 size={15}/></button>}</>}
 </div>)}</div>
 {error&&<p className="form-error" role="alert">{error}</p>}{capabilities.canManage&&<form onSubmit={save} className="form-stack member-form"><h3>{editing?'Edit project person':'Add a person'}</h3>{!editing?.owner&&<div className="form-grid"><label>Name<input required value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div>}<div className="form-grid"><label>Role tag<Choice label="Person role" value={profession} onChange={v=>{setProfession(v);if(!editing)setAccess(v==='internal'?'editor':'client')}} options={professionOptions}/></label>{!editing?.owner&&<label>Permission<Choice label="Person permission" value={access} onChange={setAccess} options={[{value:'editor',label:'Can edit plans and tasks'},{value:'client',label:'Comment and add own markups'}]}/></label>}</div><div className="member-form-actions">{editing&&<button type="button" className="button outline" onClick={reset}>Cancel edit</button>}<button className="button primary" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:editing?<Check size={16}/>:<Plus size={16}/>} {editing?'Save person':'Add person'}</button></div></form>}
 </DialogContent></Dialog>
}
