"use client";
import {useEffect,useRef,useState} from 'react';
import {Check,Copy,KeyRound,Link2,LoaderCircle,LogOut,Pencil,Plus,ShieldCheck,Trash2,UserRound} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Member,Profession,professionNames} from '@/lib/review-types';
import {Choice,professionOptions} from './review-controls';
import {AppearanceSettings} from './appearance';
import AccountSetup,{AdministratorSetup} from './account-setup';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export function AccountDialog({open,onOpenChange,request,onChanged}:{open:boolean;onOpenChange:(v:boolean)=>void;request:Requester;onChanged:()=>Promise<void>}){
 const [setupToken,setSetupToken]=useState<string|null>(null);
 const [activationToken,setActivationToken]=useState<string|null>(null);
 const [mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[profession,setProfession]=useState('internal'),[status,setStatus]=useState<{configured:boolean;emailReady:boolean;user:any}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),api=useRef(request);api.current=request;
 useEffect(()=>{if(!open)return;setError('');setMessage('');setPassword('');const account=new URLSearchParams(window.location.search).get('account');setSetupToken(account==='setup'?new URLSearchParams(window.location.hash.slice(1)).get('invite')||'':null);setActivationToken(account==='activate'?new URLSearchParams(window.location.hash.slice(1)).get('invite')||'':null);setMode(account==='recovery'?'password':'signin');if(account==='expired')setError('This link could not be completed. Sign in if your email is confirmed, or request a new password reset from this browser.');if(account==='confirmed')setMessage('Email confirmed. Your account is ready.');api.current('/api/auth').then(setStatus).catch(e=>setError(e.message));},[open]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await request('/api/auth',{method:'POST',body:JSON.stringify({action:mode,email,password,name,profession})});if(mode==='reset'){setMessage('If an account exists, its password reset link has been sent. Open it in this browser.');return}if(r.confirmation){setMessage('Check your email to confirm your account. Open the confirmation link in this browser, then sign in.');setMode('signin');setPassword('');return}setStatus(await request('/api/auth'));setPassword('');const url=new URL(window.location.href);url.searchParams.delete('account');window.history.replaceState(null,'',url);await onChanged();onOpenChange(false);toast.success(mode==='password'?'Password updated':'Signed in. Your workspace is saved to your account.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(open&&setupToken!==null)return <AccountSetup token={setupToken} request={request} onClose={()=>{setSetupToken(null);onOpenChange(false)}}/>;
 if(open&&activationToken!==null)return <AdministratorSetup token={activationToken} request={request} onClose={()=>{setActivationToken(null);onOpenChange(false)}}/>;
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v)}}><DialogContent className="account-dialog"><DialogHeader><DialogTitle>{mode==='password'?'Choose a new password':'Account settings'}</DialogTitle><DialogDescription>{status?.user?'Your account and workspace preferences.':'Choose your appearance here. Sign in to access your projects from another device.'}</DialogDescription></DialogHeader>
 <AppearanceSettings/>
 {!status&&!error&&<LoaderCircle className="spin"/>}{status?.configured===false&&<div className="account-notice">Accounts are being connected. You can continue reviewing in the demo.</div>}
 {status?.configured&&!status?.emailReady&&!status?.user&&<div className="account-notice">Sign-in is connected. New account and reset emails are still being set up. You can continue with a review link.</div>}
 {status?.user&&mode!=='password'?<div className="account-summary"><span className="account-avatar"><UserRound size={26}/></span><strong>{status.user.name}</strong><p>{status.user.email}</p><span>{professionNames[status.user.profession as Profession]}</span><button className="button outline" disabled={busy} onClick={async()=>{setBusy(true);try{await request('/api/auth',{method:'POST',body:JSON.stringify({action:'signout'})});window.location.reload()}catch(e:any){setError(e.message);setBusy(false)}}}><LogOut size={16}/> Sign out on this device</button></div>:<>
 {['signin','signup'].includes(mode)&&<Tabs value={mode} onValueChange={v=>{setMode(v);setError('');setMessage('')}}><TabsList className="account-tabs"><TabsTrigger value="signin">Sign in</TabsTrigger><TabsTrigger value="signup">Create account</TabsTrigger></TabsList></Tabs>}
 <form onSubmit={submit} className="form-stack">{mode==='signup'&&<label>Your name<input autoComplete="name" required value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label>}{mode!=='password'&&<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='reset'&&<label>{mode==='password'?'New password':'Password'}<input type="password" minLength={8} maxLength={128} autoComplete={mode==='signin'?'current-password':'new-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='signup'&&<label>Your default role tag<Choice label="Your professional role" value={profession} onChange={setProfession} options={professionOptions}/></label>}
 {message&&<p className="account-message" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <button className="button primary full" disabled={busy||!status?.configured||(['signup','reset'].includes(mode)&&!status?.emailReady)}>{busy?<LoaderCircle className="spin" size={16}/>:<ShieldCheck size={16}/>} {mode==='signin'?'Sign in':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Save password'}</button>
 {mode==='signin'&&<button type="button" className="text-button" onClick={()=>{setMode('reset');setMessage('');setError('')}}>Forgot your password?</button>}{mode==='reset'&&<button type="button" className="text-button" onClick={()=>setMode('signin')}>Back to sign in</button>}
 </form></>}
 </DialogContent></Dialog>
}
export {default as PeopleDialog} from './people-dialog';
