"use client";
import {useEffect,useState} from 'react';
import {MonitorSmartphone,Download,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
export default function DeviceLaunch({role,guest,onShare}:{role:string;guest:boolean;onShare:()=>void}){
 const [open,setOpen]=useState(false),[prompt,setPrompt]=useState<any>(null),[installed,setInstalled]=useState(false),[remember,setRemember]=useState(false),[link,setLink]=useState(''),[currentToken,setCurrentToken]=useState('');
 useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as any).standalone;setInstalled(!!standalone);const handler=(e:Event)=>{e.preventDefault();setPrompt(e)};const done=()=>{setInstalled(true);setPrompt(null)};window.addEventListener('beforeinstallprompt',handler);window.addEventListener('appinstalled',done);setCurrentToken(new URLSearchParams(location.hash.slice(1)).get('review')||'');try{setRemember(!!localStorage.getItem('octava.launch-review'))}catch{}return()=>{window.removeEventListener('beforeinstallprompt',handler);window.removeEventListener('appinstalled',done)}},[open]);
 async function install(){if(!prompt)return;await prompt.prompt();await prompt.userChoice;setPrompt(null)}
 function openLink(e:React.FormEvent){e.preventDefault();try{const url=new URL(link.trim());const token=new URLSearchParams(url.hash.slice(1)).get('review');if(url.origin!==location.origin||!token||!/^[a-f0-9-]{72}$/.test(token))throw new Error();window.location.hash='review='+token;window.location.reload()}catch{toast.error('Paste an Octava Review link created with Share.')}}
 return <><button className="icon-button device-launch-button" aria-label="Open on your devices" title="Open on your devices" onClick={()=>setOpen(true)}><MonitorSmartphone size={17}/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="devices-dialog"><DialogHeader><DialogTitle>Open on your devices</DialogTitle><DialogDescription>One web app for computer, iPad and iPhone.</DialogDescription></DialogHeader><div className="device-guide"><section><strong>Computer</strong><p>Bookmark this page. In Chrome or Edge, use the install icon in the address bar or the browser’s app menu.</p></section><section><strong>iPad & iPhone</strong><p>Open in Safari. Tap Share, then Add to Home Screen. Enable Open as Web App if offered, then tap Add.</p></section>{prompt&&!installed&&<button className="button primary" onClick={install}><Download size={16}/> Install Octava Review</button>}{installed&&<p className="form-note">You’re using the installed web app.</p>}<section><strong>The same project, on every device</strong><p>{role==='owner'?'Create a Team editor link for your other devices, or a Client review link for a client. Open that link on the other device to access the same drawings and feedback.':'Keep your review link. Open it on another device to access this same review. Your link determines what you can see and edit.'}</p>{role==='owner'&&<button className="button outline" onClick={()=>{setOpen(false);onShare()}}>Create a review link <ExternalLink size={14}/></button>}</section>{currentToken&&<label className="remember-review"><input type="checkbox" checked={remember} onChange={e=>{setRemember(e.target.checked);try{if(e.target.checked)localStorage.setItem('octava.launch-review',currentToken);else localStorage.removeItem('octava.launch-review')}catch{toast.error('This browser could not save the launch preference.')}}}/>Open this review when I launch the installed app</label>}<form onSubmit={openLink} className="open-review-form"><label htmlFor="device-review-link">Have a review link?</label><div><input id="device-review-link" type="url" placeholder="Paste your Octava Review link" value={link} onChange={e=>setLink(e.target.value)} required/><button className="button outline" disabled={!link.trim()}>Open</button></div></form><p className="form-note">An internet connection is required to open PDFs and save changes.{guest&&' Guest ownership lasts 30 days in this browser. Keep review links and export your work before the session expires.'}</p></div></DialogContent></Dialog></>;
}
