"use client";
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Download,Eraser,Hand,LoaderCircle,MessageSquare,Pencil,Redo2,Shapes,Undo2,X} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Slider} from '@/components/ui/slider';
import DrawingCanvas,{type CanvasHandle} from './drawing-canvas';
import {asMarkups,documentAssetPath,drawingQuery,type DrawingTarget,type DrawingPage,type DrawingData} from '@/lib/document-drawings';
import {inkPalette,type Markup,type Sheet} from '@/lib/review-types';
import {openPdf} from '@/lib/pdf';
import {exportDrawingPdf} from '@/lib/drawing-render';
import './document-studio.css';

type Props={projectId:string;target:DrawingTarget;title:string;headers:Record<string,string>;page?:number;onPage?:(page:number)=>void;onClose?:()=>void;onSaved?:()=>void};
export function DocumentStudioDialog(props:Props){return <Dialog open onOpenChange={v=>{if(!v)document.dispatchEvent(new CustomEvent('octava:close-studio'));}}><DialogContent className="document-studio-dialog" showCloseButton={false}><DialogHeader className="sr-only"><DialogTitle>{props.title}</DialogTitle><DialogDescription>Sketch and annotate. Changes are saved to this project.</DialogDescription></DialogHeader><DocumentStudio {...props}/></DialogContent></Dialog>;}
export default function DocumentStudio({projectId,target,title,headers,page:externalPage,onPage,onClose,onSaved}:Props){
 const [page,setPage]=useState(externalPage||1),[pages,setPages]=useState<Record<number,DrawingPage>>({}),[sheet,setSheet]=useState<Sheet|null>(null),[fileUrl,setFileUrl]=useState(''),[count,setCount]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[canEdit,setCanEdit]=useState(false),[name,setName]=useState('Reviewer'),[userId,setUserId]=useState(''),[role,setRole]=useState('client');
 const [tool,setTool]=useState('pen'),[color,setColor]=useState('#151515'),[stroke,setStroke]=useState(3),[textSize,setTextSize]=useState(24),[selected,setSelected]=useState<string|null>(null),[saving,setSaving]=useState(false),[tick,setTick]=useState(0),[exporting,setExporting]=useState(false),[exportFile,setExportFile]=useState<{url:string;name:string}|null>(null),[shapeOpen,setShapeOpen]=useState(false),[colorOpen,setColorOpen]=useState(false);
 const canvas=useRef<CanvasHandle>(null),auth=useRef(headers),all=useRef(pages),dirty=useRef(new Set<number>()),pending=useRef<Promise<boolean>|null>(null),seq=useRef(new Map<number,number>()),history=useRef(new Map<number,{undo:DrawingData[];redo:DrawingData[]}>()),pdf=useRef<any>(null),original=useRef<Uint8Array|null>(null),mounted=useRef(true),onSave=useRef(onSaved),gesture=useRef(false);auth.current=headers;all.current=pages;onSave.current=onSaved;
 const identity=target.source+':'+target.targetId,draftKey='octava.v2.drawing-draft.'+projectId+'.'+identity;
 const api=useCallback(async(url:string,init:RequestInit={})=>{const r=await fetch(url,{...init,headers:{...auth.current,...(init.body?{'Content-Type':'application/json'}:{})}});const body:any=await r.json();if(!r.ok)throw Object.assign(Error(body.error||'Could not save the drawing.'),{status:r.status});return body;},[]);
 function put(next:Record<number,DrawingPage>){all.current=next;setPages(next);}
 function remember(){try{localStorage.setItem(draftKey,JSON.stringify([...dirty.current].map(p=>all.current[p])));}catch{}}
 async function save():Promise<boolean>{if(pending.current)return pending.current;if(!dirty.current.size)return true;
  const operation=(async()=>{setSaving(true);try{while(dirty.current.size){const p=[...dirty.current][0],value=all.current[p],revision=seq.current.get(p)||0;const r=await api('/api/drawings',{method:'POST',body:JSON.stringify({projectId,target,page:p,version:value.version,data:{width:value.width,height:value.height,marks:value.marks}})});const current=all.current[p];put({...all.current,[p]:{...current,id:r.page.id,version:r.page.version,updated:r.page.updated}});if((seq.current.get(p)||0)===revision)dirty.current.delete(p);remember();onSave.current?.();}setError('');try{localStorage.removeItem(draftKey)}catch{}return true;}catch(e:any){setError(e.message);remember();return false;}finally{if(mounted.current)setSaving(false);}})();pending.current=operation;try{return await operation;}finally{pending.current=null;}
 }
 const saveRef=useRef(save);saveRef.current=save;
 useEffect(()=>{mounted.current=true;let live=true,url='';setLoading(true);setError('');
  (async()=>{const r=await api('/api/drawings?'+drawingQuery(projectId,target));if(!live)return;setCanEdit(r.canEdit);setName(r.name);setUserId(r.userId);setRole(r.role);let values=Object.fromEntries(r.pages.map((p:DrawingPage)=>[p.page,p]));
   try{const drafts=JSON.parse(localStorage.getItem(draftKey)||'[]');if(r.canEdit&&Array.isArray(drafts)&&drafts.length){for(const p of drafts){if(!p?.marks||!p.page)continue;values[p.page]=p;dirty.current.add(p.page);}toast('Recovered your unsaved drawing.');}}catch{}put(values);
   if(target.source!=='sketch'){const res=await fetch(documentAssetPath(projectId,target),{headers:auth.current});if(!res.ok)throw Error('Could not open this PDF.');const blob=await res.blob();original.current=new Uint8Array(await blob.arrayBuffer());url=URL.createObjectURL(blob);const doc=await openPdf(url);if(!live){await doc.destroy();return;}pdf.current=doc;setFileUrl(url);setCount(doc.numPages);if(page>doc.numPages){setPage(1);onPage?.(1);}}
   setLoading(false);if(dirty.current.size)setTick(t=>t+1);
  })().catch(e=>{if(live){setError(e.message);setLoading(false);}});
  return()=>{live=false;mounted.current=false;if(dirty.current.size)void saveRef.current();pdf.current?.destroy();pdf.current=null;if(url)URL.revokeObjectURL(url);};
 },[identity,projectId]);
 useEffect(()=>{if(loading||(target.source!=='sketch'&&!fileUrl))return;let live=true;setSelected(null);setSheet(null);(async()=>{let width=all.current[page]?.width||(window.innerWidth<=640?1000:1400),height=all.current[page]?.height||(window.innerWidth<=640?1400:1000);if(pdf.current){const p=await pdf.current.getPage(page),v=p.getViewport({scale:1});width=v.width;height=v.height;}if(live)setSheet({id:identity+'/'+page,type:'sheet',code:'',name:title,revision:'',page,width,height,groupId:'',...(fileUrl?{fileId:target.targetId}:{}),created:''});})().catch(e=>{if(live)setError(e.message)});return()=>{live=false;};},[page,loading,fileUrl,identity]);
 useEffect(()=>{if(externalPage&&externalPage!==page)void goPage(externalPage);},[externalPage]);
 useEffect(()=>{if(!dirty.current.size)return;const timer=setTimeout(()=>void saveRef.current(),650);return()=>clearTimeout(timer);},[tick]);
 useEffect(()=>{const timer=setInterval(async()=>{if(document.hidden||dirty.current.size||pending.current||gesture.current)return;try{const r=await api('/api/drawings?'+drawingQuery(projectId,target));if(dirty.current.size||pending.current||gesture.current)return;const next=Object.fromEntries(r.pages.map((p:DrawingPage)=>[p.page,p]));if(r.pages.some((p:DrawingPage)=>p.version!==all.current[p.page]?.version)){put(next);history.current.clear();setTick(t=>t+1);}setCanEdit(r.canEdit);}catch{}},5000);return()=>clearInterval(timer);},[identity,projectId]);
 useEffect(()=>()=>{if(exportFile)URL.revokeObjectURL(exportFile.url);},[exportFile]);
 useEffect(()=>{const end=()=>{gesture.current=false;};window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);window.addEventListener('blur',end);return()=>{window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);window.removeEventListener('blur',end);};},[]);
 const actions=useRef({close:async()=>{},undo:()=>{},redo:()=>{}});actions.current={close:async()=>{if(await save())onClose?.();},undo:()=>travel(false),redo:()=>travel(true)};
 useEffect(()=>{const flush=(e:Event)=>{(e as CustomEvent).detail.saves.push(saveRef.current());},close=()=>void actions.current.close(),warn=(e:BeforeUnloadEvent)=>{if(dirty.current.size){e.preventDefault();e.returnValue='';}},online=()=>void saveRef.current(),keys=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[contenteditable=true]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopImmediatePropagation();e.shiftKey?actions.current.redo():actions.current.undo();}};document.addEventListener('octava:flush-drawings',flush);document.addEventListener('octava:close-studio',close);window.addEventListener('beforeunload',warn);window.addEventListener('online',online);window.addEventListener('keydown',keys,true);return()=>{document.removeEventListener('octava:flush-drawings',flush);document.removeEventListener('octava:close-studio',close);window.removeEventListener('beforeunload',warn);window.removeEventListener('online',online);window.removeEventListener('keydown',keys,true);};},[]);
 const data=all.current[page]||{width:sheet?.width||1400,height:sheet?.height||1000,marks:[]},marks=asMarkups(data,identity+'/'+page);
 function update(next:DrawingData,record=true){if(!canEdit)return;if(exportFile){URL.revokeObjectURL(exportFile.url);setExportFile(null);}const current=all.current[page]||{...data,id:'',page,version:0,updated:''};if(record){const h=history.current.get(page)||{undo:[],redo:[]};h.undo.push({width:current.width,height:current.height,marks:current.marks});h.undo=h.undo.slice(-40);h.redo=[];history.current.set(page,h);}put({...all.current,[page]:{...current,...next}});dirty.current.add(page);seq.current.set(page,(seq.current.get(page)||0)+1);remember();setTick(t=>t+1);}
 function modify(next:Markup[]){update({width:data.width,height:data.height,marks:next.map(({id,kind,points,color,width,text,textSize,textStyle,author,created,creatorId,authorRole})=>({id,kind:kind as DrawingData['marks'][number]['kind'],points,color,width,...(text!==undefined?{text}:{}),...(textSize!==undefined?{textSize}:{}),...(textStyle?{textStyle}:{}),author,created,creatorId:creatorId||userId,...(authorRole?{authorRole}:{})}))});}
 function travel(redo:boolean){canvas.current?.cancelDraft();const h=history.current.get(page),from=redo?h?.redo:h?.undo,to=redo?h?.undo:h?.redo;if(!from?.length||!to)return;to.push({width:data.width,height:data.height,marks:data.marks});update(from.pop()!,false);setSelected(null);}
 async function goPage(n:number){if(!await save())return;setPage(Math.max(1,Math.min(count,n)));onPage?.(Math.max(1,Math.min(count,n)));}
 async function download(){setExporting(true);try{await save();const values=Object.values(all.current).map(p=>({page:p.page,data:p}));if(!values.length)values.push({page,data});const bytes=await exportDrawingPdf(original.current,values,pdf.current),url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=title.replace(/\.pdf$/i,'').replace(/[/\\:*?"<>|]/g,'-')+' · annotated.pdf';if(exportFile)URL.revokeObjectURL(exportFile.url);setExportFile({url,name:a.download});document.body.appendChild(a);a.click();a.remove();}catch(e:any){setError('Export failed: '+e.message);toast.error(e.message);}finally{setExporting(false);}}
 async function reload(){if(!window.confirm('Replace your unsaved drawing with the saved page? Download your copy first if you want to keep it.'))return;dirty.current.clear();localStorage.removeItem(draftKey);try{const r=await api('/api/drawings?'+drawingQuery(projectId,target));put(Object.fromEntries(r.pages.map((p:DrawingPage)=>[p.page,p])));history.current.clear();setError('');setTick(t=>t+1);}catch(e:any){setError(e.message);}}
 const h=history.current.get(page),shape=['line','arrow','rect','ellipse'].includes(tool);
 return <section className="document-studio" aria-label={target.source==='sketch'?'Meeting sketch pad':'PDF drawing workspace'} onPointerDownCapture={()=>{gesture.current=true;}} onPointerUpCapture={()=>{gesture.current=false;}} onPointerCancelCapture={()=>{gesture.current=false;}}>
  <header className="studio-header"><strong title={title}>{title}</strong>{target.source!=='sketch'&&<div className="studio-pages"><button aria-label="Previous PDF page" disabled={page<=1||loading} onClick={()=>goPage(page-1)}><ChevronLeft size={17}/></button><label><input aria-label="PDF page number" type="number" min={1} max={count} key={page} defaultValue={page} onBlur={e=>{const n=Number(e.target.value);if(n&&n!==page)void goPage(n);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>/ {count}</span></label><button aria-label="Next PDF page" disabled={page>=count||loading} onClick={()=>goPage(page+1)}><ChevronRight size={17}/></button></div>}<button aria-label="Download annotated PDF" title="Download annotated PDF" disabled={loading||exporting} onClick={download}>{exporting?<LoaderCircle className="spin" size={17}/>:<Download size={17}/>}</button>{onClose&&<button aria-label="Save and close drawing" title="Save and close" onClick={()=>actions.current.close()}><X size={18}/></button>}</header>
  {exportFile&&<div className="studio-export-ready"><Check size={15}/><span>PDF ready</span><a href={exportFile.url} download={exportFile.name}>Save PDF</a><button aria-label="Dismiss PDF download" onClick={()=>{URL.revokeObjectURL(exportFile.url);setExportFile(null);}}><X size={15}/></button></div>}
  {error&&<div className="studio-error" role="alert"><span>{error}</span>{dirty.current.size>0&&<><button onClick={()=>save()}>Retry save</button><button onClick={reload}>Reload saved</button></>}</div>}
  <div className="studio-toolbar" role="toolbar" aria-label="Drawing tools">{[{id:'pen',label:'Brush',icon:Pencil},{id:'eraser',label:'Eraser',icon:Eraser},{id:'hand',label:'Move page',icon:Hand}].map(({id,label,icon:Icon})=><button key={id} title={label} aria-label={label} aria-pressed={tool===id} disabled={!canEdit&&id!=='hand'} onClick={()=>setTool(id)}><Icon size={18}/></button>)}<Popover open={shapeOpen} onOpenChange={setShapeOpen}><PopoverTrigger asChild><button aria-label="Shape tools" title="Shapes" aria-pressed={shape} disabled={!canEdit}><Shapes size={18}/></button></PopoverTrigger><PopoverContent className="studio-shapes" sideOffset={8}>{[{id:'line',label:'Line'},{id:'arrow',label:'Arrow'},{id:'rect',label:'Rectangle'},{id:'ellipse',label:'Ellipse'}].map(s=><button key={s.id} aria-pressed={tool===s.id} onClick={()=>{setTool(s.id);setShapeOpen(false);}}>{s.label}</button>)}</PopoverContent></Popover><button aria-label="Callout text" title="Callout text" aria-pressed={tool==='text'} disabled={!canEdit} onClick={()=>setTool('text')}><MessageSquare size={18}/></button><Popover open={colorOpen} onOpenChange={setColorOpen}><PopoverTrigger asChild><button aria-label="Ink color" title="Ink color" className="studio-color" disabled={!canEdit}><span style={{background:color}}/></button></PopoverTrigger><PopoverContent className="studio-palette" align="center"><span>Ink color</span><div>{inkPalette.map(c=><button key={c.color} aria-label={c.name} title={c.name} aria-pressed={color===c.color} style={{background:c.color,color:c.contrast}} onClick={()=>{setColor(c.color);setColorOpen(false);}}>{color===c.color&&<Check size={17}/>}</button>)}</div></PopoverContent></Popover><i/><button aria-label="Undo drawing" title="Undo" disabled={!canEdit||!h?.undo.length} onClick={()=>travel(false)}><Undo2 size={18}/></button><button aria-label="Redo drawing" title="Redo" disabled={!canEdit||!h?.redo.length} onClick={()=>travel(true)}><Redo2 size={18}/></button></div>
  <div className="studio-canvas-area">{loading||!sheet?<div className="studio-loading"><LoaderCircle className="spin"/><span>{error?'The drawing could not be opened.':'Opening drawing…'}</span></div>:<DrawingCanvas key={sheet.id} ref={canvas} pdfDocument={pdf.current} blank sheet={sheet} markups={marks.map(m=>({...m,editable:canEdit&&(role!=='client'||m.creatorId===userId)}))} tasks={[]} tool={canEdit?tool:'hand'} color={color} stroke={stroke} precision={2} areaMode="rectangle" onAreaMode={()=>{}} textSize={textSize} onTextSize={setTextSize} onPrecision={()=>{}} visibility="internal" name={name} fileUrl={fileUrl||undefined} headers={{}} selected={selected} hideMarks={false} onSelect={setSelected} onMarkup={m=>modify([...asMarkups(all.current[page],sheet.id),m])} onErase={async erased=>{const ids=new Set(erased.map(m=>m.id));modify(asMarkups(all.current[page],sheet.id).filter(m=>!ids.has(m.id)));return [...ids];}} onEdit={async m=>modify(asMarkups(all.current[page],sheet.id).map(v=>v.id===m.id?m:v))} onPin={()=>{}} onPhotoPin={()=>{}} onPhotoOpen={()=>{}} onTask={()=>{}} onCalibrate={()=>{}}/>}
   {canEdit&&tool!=='hand'&&tool!=='text'&&tool!=='eraser'&&<aside className="studio-size" aria-label="Brush size"><span className="studio-stroke-sample"><i style={{width:Math.min(24,stroke),height:Math.min(24,stroke),background:color}}/></span><Slider orientation="vertical" min={1} max={40} step={1} value={[stroke]} onValueChange={([n])=>setStroke(n)} aria-label="Stroke thickness in pixels"/><label><input aria-label="Stroke width" inputMode="numeric" type="number" min={1} max={40} value={stroke} onChange={e=>setStroke(Math.max(1,Math.min(40,Number(e.target.value)||1)))}/><span>px</span></label></aside>}
  </div><footer className="studio-status" role="status"><span>{!canEdit?'View only':saving?'Saving…':dirty.current.size?'Unsaved drawing':'All changes saved'}</span><span>{target.source==='sketch'?'Meeting sketch':'PDF annotations'} · {tool==='eraser'?'Drag across marks to erase':'Two fingers to pan / zoom'}</span></footer>
 </section>;
}
