"use client";
import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Camera,Check,CheckCheck,ChevronLeft,ChevronRight,ClipboardList,Download,FileText,ImagePlus,Link2,LoaderCircle,MapPin,NotebookPen,Plus,Presentation,Search,ShoppingBag,Trash2,Users,X} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {Choice} from './review-controls';
import AssetPreview,{assetPath} from './asset-preview';
import PhotoLibraryPicker from './photo-library-picker';
import {meetingKinds,blankEntry,type Meeting,type MeetingEntry,type MeetingReport} from '@/lib/meetings';
import {uid,statusNames,type ProjectAsset,type Task} from '@/lib/review-types';
import {uploadFile,uploadThumbnail,type Requester} from '@/lib/upload-client';
import {downloadMeetingReport} from '@/lib/meeting-report';

const icons={site:Camera,selection:ShoppingBag,review:Presentation};
const descriptions={site:'Capture photos, observations and tasks.',selection:'Record products, rooms and client choices.',review:'Keep notes and decisions beside a presentation.'};
const dayLabel=(day:string)=>new Date(day+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'});
type Props={projectId:string;projectName:string;headers:Record<string,string>;request:Requester;tasks:Task[];onTask:(t:Task)=>void;onChanged:()=>Promise<unknown>;onSpecifications:()=>void};

function PresentationPane({file,page,onPage,projectId,headers}:{file:ProjectAsset;page:number;onPage:(n:number)=>void;projectId:string;headers:Record<string,string>}){
 const canvas=useRef<HTMLCanvasElement>(null),[count,setCount]=useState(1),[error,setError]=useState(''),[loading,setLoading]=useState(true),pdf=useRef<any>(null);
 useEffect(()=>{let live=true;setError('');setLoading(true);pdf.current=null;
  (async()=>{if(file.mime!=='application/pdf')throw Error('Upload a PDF copy in Presentations to review pages here.');const res=await fetch(assetPath(projectId,file),{headers});if(!res.ok)throw Error('Could not open this presentation.');const {openPdf}=await import('@/lib/pdf');const doc=await openPdf(new Uint8Array(await res.arrayBuffer()));if(!live){doc.destroy();return}pdf.current=doc;setCount(doc.numPages);if(page>doc.numPages)onPage(1);setLoading(false)})().catch(e=>{if(live){setError(e.message);setLoading(false)}});
  return()=>{live=false;pdf.current?.destroy();pdf.current=null};
 },[file.id,projectId]);
 useEffect(()=>{if(loading||!pdf.current)return;let stopped=false,render:any;const doc=pdf.current;
  (async()=>{const p=await doc.getPage(Math.max(1,Math.min(page,doc.numPages)));if(stopped||!canvas.current)return;const v=p.getViewport({scale:Math.min(1.8,1400/p.getViewport({scale:1}).width)});canvas.current.width=v.width;canvas.current.height=v.height;render=p.render({canvas:canvas.current,canvasContext:canvas.current.getContext('2d'),viewport:v});await render.promise})().catch(e=>{if(!stopped)setError(e.message)});return()=>{stopped=true;render?.cancel()};
 },[page,loading,file.id]);
 return <div className="meeting-presentation"><div className="presentation-page-nav"><span title={file.name}>{file.name}</span><button className="icon-button" aria-label="Previous presentation page" disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></button><span>{page} / {count}</span><button className="icon-button" aria-label="Next presentation page" disabled={page>=count} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></button></div><div className="presentation-page">{loading?<LoaderCircle className="spin"/>:error?<p>{error}</p>:<canvas ref={canvas} aria-label={'Presentation page '+page}/>}</div></div>;
}

export function ReportPaper({report,projectId,headers}:{report:MeetingReport;projectId:string;headers:Record<string,string>}){
 const m=report.meeting;
 return <article className="meeting-report-paper"><header><span className="report-brand">OCTAVA / {meetingKinds[m.kind].toUpperCase()}</span><span>{report.revision?'REPORT · R'+String(report.revision).padStart(2,'0'):'DRAFT · NOT ISSUED'}</span></header><h1>{m.title}</h1><p className="report-project">{report.projectName}</p><dl className="report-meta"><div><dt>Date</dt><dd>{dayLabel(m.date)}</dd></div><div><dt>Location</dt><dd>{m.location||'—'}</dd></div><div><dt>Participants</dt><dd>{m.participants||'Not recorded'}</dd></div></dl>{m.summary&&<p className="report-summary">{m.summary}</p>}{m.entries.filter(e=>e.include).map((entry,index)=>{const task=report.tasks.find(t=>t.id===entry.taskId),photos=[...new Set([...entry.photoIds,...(task?.photos||[]).map(p=>p.id)])].map(id=>report.assets.find(a=>a.id===id)).filter((a):a is ProjectAsset=>!!a),deck=report.assets.find(a=>a.id===entry.presentationId);return <section className="report-entry" key={entry.id}><div className="report-entry-heading"><span>{String(index+1).padStart(2,'0')}</span><div><small>{entry.kind==='task'?'ACTION':entry.kind.toUpperCase()}{entry.location?' / '+entry.location:''}</small><h2>{entry.title||'Untitled note'}</h2></div></div>{photos.length>0&&<div className="report-photos">{photos.map(photo=><AssetPreview key={photo.id} file={photo} projectId={projectId} headers={headers}/>)}</div>}{entry.text&&<p>{entry.text}</p>}{entry.kind==='selection'&&<dl className="report-selection">{[['Supplier',entry.vendor],['Model',entry.model],['Color / finish',[entry.color,entry.finish].filter(Boolean).join(' / ')],['Size / quantity',[entry.size,entry.quantity].filter(Boolean).join(' / ')],['Price',entry.price?entry.currency+' '+entry.price:''],['Selection',entry.selectionStatus]].filter(([,value])=>value).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}{task&&<div className="report-task-line"><span>Task #{task.number} · {statusNames[task.status]}</span><span>{task.assignee}{task.due?' · Due '+dayLabel(task.due):''}</span></div>}{deck&&<small className="report-source">{deck.name} · Page {entry.page}</small>}</section>})}{!m.entries.some(e=>e.include)&&<p>No entries included. Choose entries in Notes to build this report.</p>}<footer>{report.revision?'Issued '+new Date(report.issued).toLocaleString()+' by '+report.issuedBy:'Review this draft before issuing.'}{report.revision>0&&<span>Task status recorded at issue. Follow live tasks in the project.</span>}</footer></article>;
}

export default function Meetings({projectId,projectName,headers,request,tasks,onTask,onChanged,onSpecifications}:Props){
 const [meetings,setMeetings]=useState<Meeting[]>([]),[reports,setReports]=useState<MeetingReport[]>([]),[assets,setAssets]=useState<ProjectAsset[]>([]),[canEdit,setCanEdit]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [active,setActive]=useState<Meeting|null>(null),[mode,setMode]=useState('notes'),[report,setReport]=useState<MeetingReport|null>(null),[query,setQuery]=useState(''),[type,setType]=useState('all'),[create,setCreate]=useState(false),[newKind,setNewKind]=useState<Meeting['kind']>('site');
 const [busy,setBusy]=useState(false),[saveState,setSaveState]=useState('All changes saved'),[revision,setRevision]=useState(0),[pickerEntry,setPickerEntry]=useState<string|null>(null),[taskPicker,setTaskPicker]=useState(false),[taskQuery,setTaskQuery]=useState('');
 const [deckId,setDeckId]=useState(''),[page,setPage]=useState(1),[reviewTab,setReviewTab]=useState('notes'),[uploading,setUploading]=useState(''),[activePhoto,setActivePhoto]=useState<ProjectAsset|null>(null),[copiedLink,setCopiedLink]=useState('');
 const activeRef=useRef(active),api=useRef(request),dirty=useRef(false),editCount=useRef(0),savePromise=useRef<Promise<Meeting|null>|null>(null),errorRef=useRef(''),uploadInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null),uploadEntry=useRef<string|null>(null),opening=useRef(true);
 api.current=request;activeRef.current=active;errorRef.current=error;
 const draftKey='octava.v2.meeting-draft.'+projectId;
 function put(m:Meeting|null){activeRef.current=m;setActive(m)}
 function change(update:Partial<Meeting>){if(!activeRef.current||!canEdit)return;const m={...activeRef.current,...update};editCount.current++;dirty.current=true;put(m);setSaveState('Unsaved changes');setRevision(n=>n+1);try{localStorage.setItem(draftKey,JSON.stringify(m))}catch{}}
 function changeEntry(id:string,update:Partial<MeetingEntry>){if(activeRef.current)change({entries:activeRef.current.entries.map(e=>e.id===id?{...e,...update}:e)})}
 async function persist():Promise<Meeting|null>{
  if(savePromise.current)return savePromise.current;
  if(!dirty.current||!activeRef.current)return activeRef.current;
  const operation=(async()=>{while(dirty.current&&activeRef.current){const m=activeRef.current,seq=editCount.current;setSaveState('Saving…');
   try{const r=await api.current('/api/meetings',{method:'POST',body:JSON.stringify({action:'save',projectId,meeting:m})});
    setMeetings(old=>[r.meeting,...old.filter(x=>x.id!==m.id)]);
    if(activeRef.current?.id===m.id){const next=seq===editCount.current?r.meeting:{...activeRef.current,version:r.meeting.version,photoGroupId:r.meeting.photoGroupId};put(next);dirty.current=seq!==editCount.current;try{if(dirty.current)localStorage.setItem(draftKey,JSON.stringify(next));else localStorage.removeItem(draftKey)}catch{}}
    setSaveState('All changes saved');setError('');
   }catch(e:any){setSaveState(e.status===409?'Review conflicting changes':'Not saved · retry');setError(e.message);throw e}
  }return activeRef.current})();savePromise.current=operation;try{return await operation}finally{savePromise.current=null}
 }
 async function refresh(initial=false){
  try{const r=await api.current('/api/meetings?project='+projectId);setMeetings(r.meetings);setReports(r.reports);setAssets(r.assets);setCanEdit(r.canEdit);
   if(opening.current){opening.current=false;const params=new URLSearchParams(window.location.search),remote=r.meetings.find((m:Meeting)=>m.id===params.get('meeting')),issued=r.reports.find((p:MeetingReport)=>p.id===params.get('report'));
    let draft:Meeting|null=null;try{draft=JSON.parse(localStorage.getItem(draftKey)||'null')}catch{}
    if(draft&&r.canEdit){put(draft);dirty.current=true;setSaveState('Recovered draft · save to sync');toast('Your unsaved meeting draft was recovered.');}
    else if(remote)put(remote);if(issued){put(issued.meeting);setReport(issued);setMode('report')}
   }else if(activeRef.current&&!dirty.current&&!savePromise.current){const next=r.meetings.find((m:Meeting)=>m.id===activeRef.current?.id);if(next&&next.version!==activeRef.current.version)put(next)}
   if(!dirty.current)setError('');
  }catch(e:any){if(initial)setError(e.message)}finally{if(initial)setLoading(false)}
 }
 useEffect(()=>{void refresh(true);const timer=setInterval(()=>{if(!document.hidden)void refresh()},6000);return()=>{clearInterval(timer);if(dirty.current)void persist().catch(()=>{})}},[projectId]);
 useEffect(()=>{if(!dirty.current||errorRef.current)return;const t=setTimeout(()=>void persist().catch(()=>{}),800);return()=>clearTimeout(t)},[revision]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current||uploading){e.preventDefault();e.returnValue=''}};const online=()=>{if(dirty.current)void persist().catch(()=>{})};window.addEventListener('beforeunload',warn);window.addEventListener('online',online);return()=>{window.removeEventListener('beforeunload',warn);window.removeEventListener('online',online)}},[uploading]);
 async function choose(m:Meeting|null){try{await persist();put(m);setMode('notes');setReport(null);setError('');setDeckId('');setPage(1);setReviewTab('notes');setCopiedLink('');const url=new URL(window.location.href);url.searchParams.delete('meeting');url.searchParams.delete('report');window.history.replaceState(null,'',url)}catch{toast.error('Save or reload the current draft before leaving.')}}
 async function createMeeting(sample=false){setBusy(true);try{
  await persist();const now=new Date().toISOString(),date=now.slice(0,10),entries:MeetingEntry[]=[];
  if(sample){if(newKind==='site'){entries.push({...blankEntry('observation'),title:'Confirm terrace threshold',text:'Photograph the inside and outside levels. Check the proposed threshold detail with the builder.',location:'Living room / terrace'},{...blankEntry('decision'),title:'Review samples on site',text:'Bring the stone and timber samples together before confirming finishes.',location:'Main entrance'});}else if(newKind==='selection'){entries.push({...blankEntry('selection'),title:'Dining pendant',text:'Check the scale above the dining table before confirming the order.',location:'Dining room',vendor:'Supplier to confirm',model:'Model to confirm',finish:'Brushed brass',quantity:'2',selectionStatus:'To confirm'});}else entries.push({...blankEntry('decision'),title:'Keep the terrace connection open',text:'Review the opening width in the next presentation.',location:'Living room'},{...blankEntry('note'),title:'Kitchen layout',text:'Compare two island arrangements with the client.'});}
  const m:Meeting={id:uid(),kind:newKind,title:(sample?'Sample · ':'')+meetingKinds[newKind]+' · '+projectName.replace(' · Sample project',''),date,location:'',participants:'',summary:'',entries,version:0,created:now,updated:now,photoGroupId:null};
  const r=await api.current('/api/meetings',{method:'POST',body:JSON.stringify({action:'save',projectId,meeting:m})});setMeetings(old=>[r.meeting,...old]);put(r.meeting);dirty.current=false;setMode('notes');setReport(null);setCreate(false);setError('');setSaveState('All changes saved');
 }catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 function addEntry(kind:MeetingEntry['kind']){if(!active)return;const entry=blankEntry(kind);if(active.kind==='review'&&deckId){entry.presentationId=deckId;entry.page=page}change({entries:[...active.entries,entry]});requestAnimationFrame(()=>document.getElementById('entry-'+entry.id)?.focus())}
 async function entryAction(entry:MeetingEntry,action:'task'|'specification'){setBusy(true);try{const m=await persist();if(!m)return;const r=await api.current('/api/meetings',{method:'POST',body:JSON.stringify({projectId,action,id:m.id,version:m.version,entryId:entry.id})});put(r.meeting);setMeetings(old=>old.map(x=>x.id===r.meeting.id?r.meeting:x));await onChanged();toast.success(action==='task'?'Live task created':'Added to Specifications')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function addPhotos(files:File[]){if(!files.length||!activeRef.current)return;setBusy(true);setUploading('Preparing photos…');try{await persist();let entry=activeRef.current.entries.find(e=>e.id===uploadEntry.current);if(!entry){entry=blankEntry(activeRef.current.kind==='selection'?'selection':'observation');change({entries:[...activeRef.current.entries,entry]})}const target=entry.id,room=8-entry.photoIds.length;if(files.length>room)toast('Up to 8 photos per entry.');for(const [i,file] of files.slice(0,room).entries()){setUploading('Uploading photo '+(i+1));const r=await uploadFile(api.current,projectId,file,'document',{kind:'photo',groupId:activeRef.current?.photoGroupId},p=>setUploading('Photo '+(i+1)+' · '+p+'%'));await uploadThumbnail(api.current,projectId,r.asset.id,file).catch(()=>false);setAssets(old=>[r.asset,...old]);const current=activeRef.current!.entries.find(e=>e.id===target)!;changeEntry(target,{photoIds:[...current.photoIds,r.asset.id]});await persist()}}catch(e:any){toast.error(e.message)}finally{setBusy(false);setUploading('')}}
 async function issue(){setBusy(true);try{const m=await persist();if(!m)return;const r=await api.current('/api/meetings',{method:'POST',body:JSON.stringify({projectId,action:'issue',id:m.id,version:m.version,reportId:uid()})});setReports(old=>[r.report,...old]);setReport(r.report);setMode('report');toast.success('Report R'+r.report.revision+' issued. Download the PDF to send it.')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function exportReport(saveToFiles=false){if(!displayReport)return;setBusy(true);try{const file=await downloadMeetingReport(displayReport,projectId,headers,!saveToFiles);if(saveToFiles){await uploadFile(api.current,projectId,file,'document',{kind:'file'});toast.success('Report PDF saved in Files')}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function copyLink(){if(!report)return;const url=new URL(window.location.origin);url.searchParams.set('project',projectId);url.searchParams.set('meeting',report.meetingId);url.searchParams.set('report',report.id);setCopiedLink(url.href);try{await navigator.clipboard.writeText(url.href);toast.success('Link copied. The recipient needs access to this V2 project.')}catch{toast('Select and copy the link below.')}}
 const displayReport:MeetingReport|null=report||(active?{id:'draft',meetingId:active.id,revision:0,issued:'',issuedBy:'',projectName,meeting:active,tasks,assets}:null);
 const modelActions=useRef<any>(null);modelActions.current={meetings,reports,choose,canEdit,setCreate,setNewKind};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const definitions=[
   {name:'list_project_meetings',title:'List project meetings',description:'Read the saved meeting summaries and issued report revisions in the open project.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Use an empty object.');const state=modelActions.current;return {meetings:state.meetings.map((m:Meeting)=>({id:m.id,title:m.title,kind:m.kind,date:m.date,entries:m.entries.length})),reports:state.reports.map((r:MeetingReport)=>({id:r.id,meetingId:r.meetingId,revision:r.revision}))}}},
   {name:'open_project_meeting',title:'Open a meeting',description:'Open an existing meeting in the visible workspace. Any current draft is saved first.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||typeof input.id!=='string'||Object.keys(input).some(k=>k!=='id'))throw Error('A meeting id is required.');const state=modelActions.current,m=state.meetings.find((m:Meeting)=>m.id===input.id);if(!m)throw Error('Meeting not found.');await persist();await state.choose(m);await new Promise(requestAnimationFrame);return {opened:m.id}}},
   {name:'start_meeting_creation',title:'Start a meeting',description:'Open the meeting creation dialog with a type selected. This does not create a meeting; finish using the visible Create meeting button.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['site','selection','review']}},required:['kind'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||!['site','selection','review'].includes(input.kind)||Object.keys(input).some(k=>k!=='kind'))throw Error('Choose site, selection or review.');const state=modelActions.current;if(!state.canEdit)throw Error('Only editors can create meetings.');state.setNewKind(input.kind);state.setCreate(true);await new Promise(requestAnimationFrame);return {dialogOpened:true,kind:input.kind}}}
  ];for(const definition of definitions){try{Promise.resolve(context.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort();
 },[]);
 const activeReports=reports.filter(r=>r.meetingId===active?.id),deck=assets.find(a=>a.id===deckId),hasActions=active?.entries.some(e=>e.taskId),list=meetings.filter(m=>(type==='all'||m.kind===type)&&[m.title,m.location,m.participants].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section className={'meetings-workspace '+(active?'meeting-open':'')} aria-label="Meetings">
 {!active?<><div className="meeting-list-header"><div><span className="eyebrow">PROJECT JOURNAL</span><h1>Meetings</h1><p>Notes, decisions and follow-up in one place.</p></div>{canEdit&&<button className="button primary" onClick={()=>setCreate(true)}><Plus size={17}/> New meeting</button>}</div><div className="meeting-list-controls"><Tabs value={type} onValueChange={setType}><TabsList variant="line"><TabsTrigger value="all">All</TabsTrigger>{Object.entries(meetingKinds).map(([value,label])=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList></Tabs><label className="searchbox"><Search size={16}/><input aria-label="Search meetings" placeholder="Search meetings…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{error&&<div className="meeting-error" role="alert">{error}<button onClick={()=>refresh(true)}>Retry</button></div>}{loading?<div className="meeting-empty"><LoaderCircle className="spin"/><p>Opening meetings…</p></div>:list.length?<div className="meeting-list">{list.map(m=>{const Icon=icons[m.kind],count=reports.filter(r=>r.meetingId===m.id).length;return <button className="meeting-list-row" key={m.id} onClick={()=>choose(m)}><span className={'meeting-type-icon '+m.kind}><Icon size={22}/></span><div><small>{meetingKinds[m.kind]} · {dayLabel(m.date)}</small><h2>{m.title}</h2><p>{m.location||m.participants||m.entries.length+' entries'}</p></div><span className="meeting-list-state">{count?'R'+String(count).padStart(2,'0')+' issued':'Draft'}<ChevronRight size={17}/></span></button>})}</div>:<div className="meeting-template-grid">{Object.entries(meetingKinds).map(([kind,label])=>{const Icon=icons[kind as Meeting['kind']];return <button disabled={!canEdit} key={kind} onClick={()=>{setNewKind(kind as Meeting['kind']);setCreate(true)}}><Icon size={29}/><h2>{label}</h2><p>{descriptions[kind as Meeting['kind']]}</p>{canEdit&&<span><Plus size={16}/> Start meeting</span>}</button>})}</div>}</>:<>
 <header className="meeting-topbar"><button className="icon-button" aria-label="Back to meetings" disabled={busy} onClick={()=>choose(null)}><ArrowLeft size={19}/></button><div><small>{meetingKinds[active.kind]}</small><h1>{active.title}</h1></div><span className="meeting-save-state" role="status">{saveState==='All changes saved'?<CheckCheck size={15}/>:<LoaderCircle size={15}/>}<span>{saveState}</span></span>{saveState!=='All changes saved'&&saveState!=='Saving…'&&<button className="button outline" disabled={busy} onClick={()=>persist().catch(()=>{})}>Save</button>}<button className="button outline" disabled={busy} onClick={()=>{setMode(mode==='notes'?'report':'notes');setReport(null)}}><FileText size={16}/>{mode==='notes'?'Report preview':'Edit notes'}</button></header>
 {error&&<div className="meeting-error" role="alert"><span>{error}</span><button onClick={()=>persist().catch(()=>{})}>Retry save</button><button onClick={()=>{if(window.confirm('Replace your unsaved draft with the latest saved meeting?')){dirty.current=false;localStorage.removeItem(draftKey);const latest=meetings.find(m=>m.id===active.id);if(latest)put(latest);setError('');setSaveState('All changes saved')}}}>Reload latest</button></div>}
 {mode==='report'&&displayReport?<div className="meeting-report-area"><div className="report-toolbar"><Choice label="Report revision" value={report?.id||'draft'} onChange={id=>setReport(reports.find(r=>r.id===id)||null)} options={[{value:'draft',label:'Current draft'},...activeReports.map(r=>({value:r.id,label:'R'+String(r.revision).padStart(2,'0')+' · '+new Date(r.issued).toLocaleDateString()}))]}/><span>{report?'Issued snapshot':'Only checked entries are included'}</span>{report?<><button className="button outline" disabled={busy} onClick={copyLink}><Link2 size={15}/> Copy link</button><button className="button outline" disabled={busy} onClick={()=>exportReport(true)}>Save to Files</button></>:canEdit&&<button className="button primary" disabled={busy||!active.entries.some(e=>e.include)} onClick={issue}><Check size={15}/> Issue report</button>}<button className="button outline" disabled={busy} onClick={()=>exportReport()}><Download size={15}/> PDF</button></div>{report&&<p className="report-sharing-note">This link follows project access. Download the PDF to send it to someone outside V2. No email is sent automatically.</p>}{copiedLink&&<input className="report-copy-link" aria-label="Report link" readOnly value={copiedLink} onFocus={e=>e.target.select()}/>}<ReportPaper report={displayReport} projectId={projectId} headers={headers}/></div>:<div className={'meeting-notes-layout '+(active.kind==='review'?'with-presentation':'')+' review-tab-'+reviewTab}>
 {active.kind==='review'&&<div className="mobile-review-switch"><button className={reviewTab==='notes'?'active':''} onClick={()=>setReviewTab('notes')}>Notes</button><button className={reviewTab==='presentation'?'active':''} onClick={()=>setReviewTab('presentation')}>Presentation</button></div>}
 {active.kind==='review'&&<aside className="meeting-deck-panel"><Choice label="Meeting presentation" value={deckId||'none'} onChange={id=>{setDeckId(id==='none'?'':id);setPage(1)}} options={[{value:'none',label:'Choose a presentation'},...assets.filter(a=>a.kind==='presentation').map(a=>({value:a.id,label:a.name}))]}/>{deck?<PresentationPane file={deck} page={page} onPage={setPage} projectId={projectId} headers={headers}/>:<div className="meeting-empty"><Presentation size={32}/><p>Choose a presentation from this project.</p><small>Upload a PDF in Presentations to review it page by page.</small></div>}{deck&&canEdit&&<button className="button outline" onClick={()=>{addEntry('note');setReviewTab('notes')}}><Plus size={16}/> Note on page {page}</button>}</aside>}
 <div className="meeting-notes-column"><Collapsible className="meeting-details-disclosure"><CollapsibleTrigger className="meeting-details-toggle"><Users size={16}/><span>Meeting details</span><small>{dayLabel(active.date)}</small><ChevronRight size={16}/></CollapsibleTrigger><CollapsibleContent><fieldset disabled={!canEdit||busy} className="meeting-details"><label className="meeting-title-field">Meeting title<input aria-label="Meeting title" value={active.title} maxLength={200} onChange={e=>change({title:e.target.value})}/></label><div className="meeting-meta-fields"><label>Date<input type="date" value={active.date} onChange={e=>change({date:e.target.value})}/></label><label>Location<input value={active.location} maxLength={200} placeholder={active.kind==='site'?'On site':'Store, room or online'} onChange={e=>change({location:e.target.value})}/></label><label className="meeting-participants">Participants<input value={active.participants} maxLength={3000} placeholder="Names of people attending" onChange={e=>change({participants:e.target.value})}/></label></div><label>Summary<textarea rows={2} value={active.summary} maxLength={5000} placeholder="Main points or purpose of this meeting" onChange={e=>change({summary:e.target.value})}/></label></fieldset></CollapsibleContent></Collapsible>
 {canEdit&&<div className="meeting-add-bar">{active.kind==='site'?<><button className="button primary" disabled={busy} onClick={()=>{uploadEntry.current=null;cameraInput.current?.click()}}><Camera size={17}/> Take photo</button><button className="button outline" disabled={busy} onClick={()=>addEntry('observation')}><Plus size={16}/> Observation</button></>:active.kind==='selection'?<button className="button primary" disabled={busy} onClick={()=>addEntry('selection')}><Plus size={16}/> Add product</button>:<><button className="button primary" disabled={busy} onClick={()=>addEntry('note')}><Plus size={16}/> Note</button><button className="button outline" disabled={busy} onClick={()=>addEntry('decision')}><Check size={16}/> Decision</button></>}<button className="button outline" disabled={busy} onClick={()=>addEntry('task')}><ClipboardList size={16}/> Task</button>{active.kind==='site'&&<button className="button quiet" disabled={busy} onClick={()=>{setTaskPicker(true);setTaskQuery('')}}><Link2 size={15}/> Existing task</button>}</div>}
 {uploading&&<div className="meeting-upload-state" role="status"><LoaderCircle className="spin" size={16}/>{uploading} · Keep this screen open</div>}
 {!active.entries.length&&<div className="meeting-empty"><NotebookPen size={30}/><p>{active.kind==='selection'?'Add the first product you are considering.':'Capture the first point from this meeting.'}</p>{active.kind==='site'&&<small>A photo or note can become a task whenever it needs follow-up.</small>}</div>}
 <div className="meeting-entries">{active.entries.map((entry,index)=>{const linkedTask=tasks.find(t=>t.id===entry.taskId),photos=entry.photoIds.map(id=>assets.find(a=>a.id===id)).filter((a):a is ProjectAsset=>!!a),isSelection=entry.kind==='selection';return <article key={entry.id} className={'meeting-entry '+(entry.include?'':'excluded')}><header><span className="entry-number">{String(index+1).padStart(2,'0')}</span><Choice label={'Entry '+(index+1)+' type'} value={entry.kind} disabled={!canEdit||busy||!!entry.taskId||!!entry.specificationId} onChange={kind=>changeEntry(entry.id,{kind:kind as MeetingEntry['kind']})} options={['observation','task','selection','note','decision'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))}/><label className="report-include"><Checkbox checked={entry.include} disabled={!canEdit||busy} onCheckedChange={checked=>changeEntry(entry.id,{include:checked===true})}/><span>In report</span></label>{canEdit&&<button className="icon-button" disabled={busy} aria-label={'Remove entry '+(index+1)} onClick={()=>{if(window.confirm('Remove this meeting entry? Linked tasks and specifications will remain.'))change({entries:active.entries.filter(e=>e.id!==entry.id)})}}><Trash2 size={15}/></button>}</header>
 <div className={'entry-main '+(isSelection?'selection-entry':'')}><div className="entry-photo-area">{photos.length>0?<div className="entry-photos">{photos.map(photo=><div className="entry-photo" key={photo.id}><button onClick={()=>setActivePhoto(photo)} aria-label={'View '+photo.name}><AssetPreview file={photo} projectId={projectId} headers={headers}/></button>{canEdit&&<button className="remove-entry-photo" aria-label={'Unlink '+photo.name} disabled={busy} onClick={()=>changeEntry(entry.id,{photoIds:entry.photoIds.filter(id=>id!==photo.id)})}><X size={14}/></button>}</div>)}</div>:isSelection&&<button className="product-photo-empty" disabled={!canEdit||busy} onClick={()=>{uploadEntry.current=entry.id;uploadInput.current?.click()}}><ImagePlus size={25}/><span>Add photo</span></button>}{canEdit&&entry.photoIds.length<8&&<div className="entry-photo-actions"><button disabled={busy} onClick={()=>{uploadEntry.current=entry.id;cameraInput.current?.click()}}><Camera size={15}/><span>Camera</span></button><button disabled={busy} onClick={()=>{uploadEntry.current=entry.id;uploadInput.current?.click()}}><ImagePlus size={15}/><span>Upload</span></button><button disabled={busy} onClick={()=>setPickerEntry(entry.id)}>Library</button></div>}</div>
 <fieldset disabled={!canEdit||busy} className="entry-fields"><input id={'entry-'+entry.id} className="entry-title" aria-label={'Entry '+(index+1)+' title'} value={entry.title} maxLength={200} placeholder={isSelection?'Product or material name':'What did you discuss or notice?'} onChange={e=>changeEntry(entry.id,{title:e.target.value})}/><input className="entry-location" aria-label={'Entry '+(index+1)+' location'} value={entry.location} maxLength={200} placeholder="Room or location" onChange={e=>changeEntry(entry.id,{location:e.target.value})}/><textarea aria-label={'Entry '+(index+1)+' notes'} rows={3} value={entry.text} maxLength={10000} placeholder={isSelection?'Description, use or anything to confirm':'Notes, decision or what needs to happen'} onChange={e=>changeEntry(entry.id,{text:e.target.value})}/>{isSelection&&<><div className="selection-fields">{(['vendor','model','color','finish','size','quantity'] as const).map(key=><label key={key}>{key==='vendor'?'Supplier':key[0].toUpperCase()+key.slice(1)}<input value={entry[key]} maxLength={key==='quantity'?80:120} placeholder="Optional" onChange={e=>changeEntry(entry.id,{[key]:e.target.value})}/></label>)}<label>Quoted price<input inputMode="decimal" value={entry.price} maxLength={40} placeholder="Optional" onChange={e=>changeEntry(entry.id,{price:e.target.value})}/></label><label>Currency<Choice label="Selection currency" value={entry.currency} onChange={currency=>changeEntry(entry.id,{currency:currency as MeetingEntry['currency']})} options={['USD','CRC','EUR','GBP','CAD','AUD','MXN','CHF'].map(value=>({value,label:value}))}/></label></div><Choice label="Selection status" value={entry.selectionStatus} onChange={value=>changeEntry(entry.id,{selectionStatus:value as MeetingEntry['selectionStatus']})} options={['Considering','Selected','To confirm'].map(value=>({value,label:value}))}/></>}</fieldset></div>
 <footer>{entry.presentationId&&<button className="entry-page-link" onClick={()=>{setDeckId(entry.presentationId!);setPage(entry.page);setReviewTab('presentation')}}><Presentation size={14}/> {assets.find(a=>a.id===entry.presentationId)?.name||'Presentation'} · p.{entry.page}</button>}{linkedTask?<button className="entry-task-link" onClick={()=>onTask(linkedTask)}><ClipboardList size={15}/> #{linkedTask.number} · {statusNames[linkedTask.status]} · {linkedTask.assignee}<ArrowUpRight size={14}/></button>:entry.taskId?<button onClick={()=>changeEntry(entry.id,{taskId:null})}>Task unavailable · Unlink</button>:!isSelection&&canEdit&&<button className="entry-task-link" disabled={busy||!entry.title.trim()} onClick={()=>entryAction(entry,'task')}><Plus size={15}/>{entry.kind==='task'?'Create live task':'Make task'}</button>}{isSelection&&(entry.specificationId?<button onClick={onSpecifications}><Check size={15}/> In Specifications <ArrowUpRight size={14}/></button>:canEdit&&<button disabled={busy||!entry.title.trim()} onClick={()=>entryAction(entry,'specification')}><Plus size={15}/> Add to Specifications</button>)}</footer></article>})}</div>
 {active.entries.length>0&&<div className="meeting-end-note">{active.entries.length} entries{hasActions?' · Tasks remain live in the project':''}<button disabled={busy} onClick={()=>{setReport(null);setMode('report')}}>Review report <ArrowUpRight size={15}/></button></div>}
 </div></div>}
 </>}
 <input ref={uploadInput} hidden type="file" multiple accept="image/*" onChange={e=>{void addPhotos(Array.from(e.target.files||[]));e.target.value=''}}/><input ref={cameraInput} hidden type="file" accept="image/*" capture="environment" onChange={e=>{void addPhotos(Array.from(e.target.files||[]));e.target.value=''}}/>
 <Dialog open={create} onOpenChange={v=>!busy&&setCreate(v)}><DialogContent className="new-meeting-dialog"><DialogHeader><DialogTitle>Start a meeting</DialogTitle><DialogDescription>Choose the format. You can mix photos, notes and tasks in any meeting.</DialogDescription></DialogHeader><div className="meeting-template-options">{Object.entries(meetingKinds).map(([kind,label])=>{const Icon=icons[kind as Meeting['kind']];return <button aria-pressed={newKind===kind} key={kind} className={newKind===kind?'active':''} onClick={()=>setNewKind(kind as Meeting['kind'])}><Icon size={21}/><span><strong>{label}</strong><small>{descriptions[kind as Meeting['kind']]}</small></span>{newKind===kind&&<Check size={18}/>}</button>})}</div><div className="meeting-create-actions"><button className="button outline" disabled={busy} onClick={()=>createMeeting(true)}>Try with sample notes</button><button className="button primary" disabled={busy} onClick={()=>createMeeting()}>{busy?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>} Create meeting</button></div></DialogContent></Dialog>
 <Dialog open={taskPicker} onOpenChange={setTaskPicker}><DialogContent className="meeting-task-picker"><DialogHeader><DialogTitle>Bring in an existing task</DialogTitle><DialogDescription>The task stays linked to its original record.</DialogDescription></DialogHeader><input aria-label="Find existing task" placeholder="Search tasks…" value={taskQuery} onChange={e=>setTaskQuery(e.target.value)}/><div>{tasks.filter(t=>t.status!=='done'&&!active?.entries.some(e=>e.taskId===t.id)&&(t.title+t.number).toLowerCase().includes(taskQuery.toLowerCase())).map(task=><button key={task.id} onClick={()=>{if(!active)return;change({entries:[...active.entries,{...blankEntry('task'),taskId:task.id,title:task.title,text:task.description,location:task.location||'',photoIds:(task.photos||[]).map(p=>p.id)}]});setTaskPicker(false)}}><span>#{task.number}</span><strong>{task.title}</strong><span>{statusNames[task.status]}</span></button>)}</div></DialogContent></Dialog>
 <PhotoLibraryPicker open={!!pickerEntry} onOpenChange={v=>!v&&setPickerEntry(null)} projectId={projectId} headers={headers} request={request} purpose="specification" onChoose={file=>{const entry=activeRef.current?.entries.find(e=>e.id===pickerEntry);if(entry){setAssets(old=>old.some(f=>f.id===file.id)?old:[...old,file]);changeEntry(entry.id,{photoIds:[...new Set([...entry.photoIds,file.id])].slice(0,8)})}setPickerEntry(null)}}/>
 <Dialog open={!!activePhoto} onOpenChange={v=>!v&&setActivePhoto(null)}><DialogContent className="attachment-lightbox"><DialogHeader><DialogTitle>{activePhoto?.name||'Photo'}</DialogTitle><DialogDescription>Meeting photo</DialogDescription></DialogHeader>{activePhoto&&<AssetPreview file={activePhoto} projectId={projectId} headers={headers} large/>}</DialogContent></Dialog>
 </section>;
}
