"use client";
import {useEffect,useRef,useState} from 'react';
import {Camera,Check,Folder,Heart,LoaderCircle,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Choice} from './review-controls';
import AssetPreview from './asset-preview';
import type {PhotoGroup,ProjectAsset} from '@/lib/review-types';
import type {Requester} from '@/lib/upload-client';

export default function PhotoLibraryPicker({open,onOpenChange,projectId,headers,request,onChoose,purpose='pin'}:{open:boolean;onOpenChange:(v:boolean)=>void;projectId:string;headers:Record<string,string>;request:Requester;onChoose:(file:ProjectAsset)=>void;purpose?:'pin'|'specification'}){
 const [photos,setPhotos]=useState<ProjectAsset[]>([]),[groups,setGroups]=useState<PhotoGroup[]>([]),[group,setGroup]=useState('all'),[query,setQuery]=useState(''),[collection,setCollection]=useState('all'),[userId,setUserId]=useState(''),[selected,setSelected]=useState<string|null>(null),[limit,setLimit]=useState(60),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const api=useRef(request),scroll=useRef<HTMLDivElement>(null),more=useRef<HTMLDivElement>(null);api.current=request;
 useEffect(()=>{if(!open)return;let live=true;setLoading(true);setError('');setSelected(null);setGroup('all');setCollection('all');setQuery('');api.current('/api/documents?project='+encodeURIComponent(projectId)).then(r=>{if(live){setPhotos(r.assets.filter((f:ProjectAsset)=>f.kind==='photo'));setGroups(r.groups||[]);setUserId(r.userId)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[open,projectId,retry]);
 useEffect(()=>{setLimit(60);scroll.current?.scrollTo({top:0})},[group,query,collection]);
 const matching=photos.filter(f=>(group==='all'||group==='ungrouped'&&!f.groupId||f.groupId===group)&&(collection==='all'||collection==='mine'&&f.creatorId===userId||collection==='liked'&&f.liked)&&(!query||(f.name+' '+f.author).toLowerCase().includes(query.toLowerCase()))),shown=matching.slice(0,limit),chosen=photos.find(f=>f.id===selected);
 const days=Array.from(new Set(shown.map(f=>f.created.slice(0,10))));
 useEffect(()=>{if(!open||loading||!more.current||limit>=matching.length)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setLimit(n=>n+60)},{root:scroll.current,rootMargin:'240px'});observer.observe(more.current);return()=>observer.disconnect()},[open,loading,limit,matching.length]);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="photo-library-dialog"><DialogHeader><DialogTitle>Choose a photo</DialogTitle><DialogDescription>{purpose==='pin'?'Select a photo, then tap the plan to place its pin. People who can view that plan can open the linked photo.':'Choose a product photo or reference image for this specification.'}</DialogDescription></DialogHeader>
  <div className="photo-library-controls"><label className="searchbox"><Search size={16}/><input autoComplete="off" aria-label="Search photo library" placeholder="Search photos" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="photo-library-group"><Folder size={17}/><Choice label="Filter photo library by group" value={group} onChange={setGroup} options={[{value:'all',label:'All groups'},{value:'ungrouped',label:'Ungrouped'},...groups.map(g=>({value:g.id,label:g.name}))]}/></div><div className="photo-library-collections" aria-label="Photo library collections">{[{id:'all',label:'All photos'},{id:'mine',label:'My photos'},{id:'liked',label:'Liked photos'}].map(item=><button key={item.id} aria-pressed={collection===item.id} onClick={()=>setCollection(item.id)}>{item.label}</button>)}<span>{matching.length} photos</span></div></div>
  <div className="photo-library-feed" ref={scroll}>{loading?<div className="overview-loading"><LoaderCircle className="spin"/> Loading photos…</div>:error?<div className="overview-empty"><p role="alert">{error}</p><button className="button outline" onClick={()=>setRetry(n=>n+1)}>Try again</button></div>:!matching.length?<div className="overview-empty"><Camera size={32}/><h2>No photos here</h2><p>{photos.length?'Try another group or search.':'Add photos to this project in Photos first.'}</p></div>:days.map(day=><section className="photo-library-day" key={day}><h3>{new Date(day+'T12:00:00').toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}</h3><div className="photo-library-grid">{shown.filter(f=>f.created.startsWith(day)).map(file=><button key={file.id} className={'photo-library-tile '+(selected===file.id?'selected':'')} aria-label={'Choose '+file.name} aria-pressed={selected===file.id} title={file.name} onClick={()=>setSelected(file.id)}><AssetPreview file={file} projectId={projectId} headers={headers}/><span className="photo-library-check">{selected===file.id&&<Check size={16}/>}</span>{file.liked&&<Heart className="photo-library-heart" size={15} fill="currentColor"/>}<span className="photo-library-name">{file.name}</span></button>)}</div></section>)}{!loading&&limit<matching.length&&<div ref={more} className="photo-library-more"><button className="button outline" onClick={()=>setLimit(n=>n+60)}>Load more photos</button></div>}</div>
  <div className="photo-library-footer"><span>{chosen?.name||'Choose one photo'}</span><button className="button primary" disabled={!chosen} onClick={()=>chosen&&onChoose(chosen)}><Camera size={16}/> {purpose==='pin'?'Place photo pin':'Use photo'}</button></div>
 </DialogContent></Dialog>
}
