"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,FolderOpen,Grid2X2,Rows3,Search,Plus,Upload,LoaderCircle,Users,LockKeyhole,FolderPlus,ChevronDown,ChevronRight,Pencil} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Audience,Project,Sheet,Task,PlanFolder} from '@/lib/review-types';
import PlanPreview from './plan-preview';
import {AudienceSelect,Choice} from './review-controls';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export function ProjectOverview({request,onOpen,onCreate,headers,guest,onAccount,refreshKey,canCreate}:{request:Requester;onOpen:(id:string)=>void;onCreate:()=>void;headers:Record<string,string>;guest:boolean;onAccount:()=>void;refreshKey:string;canCreate:boolean}){
 const [projects,setProjects]=useState<Project[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),api=useRef(request);api.current=request;
 useEffect(()=>{
  let live=true,busy=false;setLoading(true);
  const refresh=async()=>{if(busy)return;busy=true;try{const r=await api.current('/api/projects',{signal:AbortSignal.timeout(12000)});if(live){setProjects(r.projects);setError('')}}catch(e:any){if(live)setError(e.message)}finally{busy=false;if(live)setLoading(false)}};
  const resume=()=>{if(!document.hidden)void refresh()};
  void refresh();const timer=setInterval(resume,5000);window.addEventListener('focus',resume);window.addEventListener('online',resume);document.addEventListener('visibilitychange',resume);
  return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',resume);window.removeEventListener('online',resume);document.removeEventListener('visibilitychange',resume)};
 },[refreshKey]);
 const shown=projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
 return <main className="overview-page"><div className="overview-heading"><div><span className="eyebrow">OCTAVA REVIEW</span><h1>Projects</h1><p>{projects.length} project{projects.length===1?'':'s'} in your workspace</p></div>{canCreate&&<button className="button primary" onClick={onCreate}><Plus size={17}/> New project</button>}</div>
 <div className="overview-toolbar"><label className="searchbox"><Search size={17}/><input aria-label="Search projects" placeholder="Search projects" value={query} onChange={e=>setQuery(e.target.value)}/></label>{guest&&<button className="account-nudge" onClick={onAccount}>Save your workspace to an account <ArrowUpRight size={15}/></button>}</div>
 {error&&<div className="error-banner">{error}</div>}{loading?<div className="overview-loading"><LoaderCircle className="spin"/> Opening projects</div>:<div className="project-grid">{shown.map(p=><button className="project-card" key={p.id} onClick={()=>onOpen(p.id)}><div className="project-cover"><PlanPreview sheet={p.cover} projectId={p.id} headers={headers}/><span className="project-open-icon"><ArrowUpRight size={20}/></span></div><div className="project-card-body"><h2>{p.name}</h2><div><span>{p.planCount||0} plans</span><span>{p.taskCount||0} open tasks</span><span>{p.role==='owner'?'Administrator':p.role==='editor'?'Team':'Review'}</span></div></div></button>)}</div>}
 {!loading&&!shown.length&&<div className="overview-empty"><FolderOpen size={35}/><h2>{query?'No matching projects':canCreate?'Your next project starts here':'No projects assigned'}</h2><p>{query?'Try another project name.':canCreate?'Create a project and import its plans.':'Your administrator needs to enable a project for you. It will appear here automatically.'}</p>{!query&&canCreate&&<button className="button outline" onClick={onCreate}><Plus size={16}/> Create project</button>}</div>}
 </main>
}
export function PlanOverview({project,sheets,tasks,folders,headers,onOpen,onUpload,canUpload,canManage,canOrganize,onAudience,onFolder,onMove}:{project:Project;sheets:Sheet[];tasks:Task[];folders:PlanFolder[];headers:Record<string,string>;onOpen:(s:Sheet)=>void;onUpload:(folderId?:string)=>void;canUpload:boolean;canManage:boolean;canOrganize:boolean;onAudience:(s:Sheet,a:Audience)=>Promise<void>;onFolder:(action:'create'|'rename',name:string,folder?:PlanFolder)=>Promise<void>;onMove:(s:Sheet,folderId:string)=>Promise<void>}){
 const [query,setQuery]=useState(''),[layout,setLayout]=useState('tiles'),[sort,setSort]=useState('code'),[busy,setBusy]=useState(''),[folderFilter,setFolderFilter]=useState('all'),[collapsed,setCollapsed]=useState(new Set<string>()),[folderOpen,setFolderOpen]=useState(false),[folderName,setFolderName]=useState(''),[editingFolder,setEditingFolder]=useState<PlanFolder|undefined>();
 useEffect(()=>{try{const value=localStorage.getItem('octava.plan-layout');if(value==='rows'||value==='tiles')setLayout(value)}catch{}},[]);
 useEffect(()=>{setFolderFilter('all');setCollapsed(new Set())},[project.id]);
 const shown=sheets.filter(s=>(s.name+' '+s.code+' '+s.revision).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='recent'?b.created.localeCompare(a.created):a.code.localeCompare(b.code,undefined,{numeric:true}));
 const sections=[...folders.map(f=>({...f,sheets:shown.filter(s=>s.folderId===f.id)})),{id:'unfiled',name:'Unfiled plans',sheets:shown.filter(s=>!s.folderId||!folders.some(f=>f.id===s.folderId)),version:0,created:''}].filter(f=>(folderFilter==='all'||folderFilter===f.id)&&(!query||f.sheets.length)&&(f.id!=='unfiled'||f.sheets.length||!folders.length));
 const folderOptions=[{value:'unfiled',label:'Unfiled'},...folders.map(f=>({value:f.id,label:f.name}))];
 function folderDialog(folder?:PlanFolder){setEditingFolder(folder);setFolderName(folder?.name||'');setFolderOpen(true)}
 return <main className="overview-page plans-overview"><div className="overview-heading"><div><span className="eyebrow">{project.name}</span><h1>Plans</h1><p>{sheets.length} current plan{sheets.length===1?'':'s'}{folders.length?' · '+folders.length+' folder'+(folders.length===1?'':'s'):''}</p></div><div className="overview-heading-actions">{canOrganize&&<button className="button outline" onClick={()=>folderDialog()}><FolderPlus size={17}/> New folder</button>}{canUpload&&<button className="button primary" onClick={()=>onUpload(folderFilter==='all'||folderFilter==='unfiled'?undefined:folderFilter)}><Upload size={17}/> Import PDF</button>}</div></div>
 <div className="overview-toolbar"><label className="searchbox"><Search size={17}/><input aria-label="Search plans" placeholder="Search plan name, number or revision" value={query} onChange={e=>setQuery(e.target.value)}/></label>{folders.length>0&&<Choice label="Filter plans by folder" value={folderFilter} onChange={setFolderFilter} options={[{value:'all',label:'All folders'},...folderOptions]}/>}<label className="sort-label">Sort <select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort plans"><option value="code">Plan number</option><option value="recent">Newest first</option></select></label><Tabs value={layout} onValueChange={v=>{setLayout(v);try{localStorage.setItem('octava.plan-layout',v)}catch{}}}><TabsList className="layout-switch"><TabsTrigger value="tiles" aria-label="Small plan tiles"><Grid2X2 size={17}/></TabsTrigger><TabsTrigger value="rows" aria-label="Full width plans"><Rows3 size={17}/></TabsTrigger></TabsList></Tabs></div>
 {sections.map(group=><section className="plan-folder-section" key={group.id}>{folders.length>0&&<div className="plan-folder-heading"><button className="folder-heading-toggle" aria-expanded={!collapsed.has(group.id)||!!query} onClick={()=>setCollapsed(old=>{const next=new Set(old);next.has(group.id)?next.delete(group.id):next.add(group.id);return next})}>{collapsed.has(group.id)&&!query?<ChevronRight size={15}/>:<ChevronDown size={15}/>}<FolderOpen size={17}/><h2>{group.name}</h2><span>{group.sheets.length}</span></button>{canOrganize&&group.id!=='unfiled'&&<button className="icon-button" aria-label={'Rename '+group.name} onClick={()=>folderDialog(group)}><Pencil size={14}/></button>}</div>}{(!collapsed.has(group.id)||!!query)&&<><div className={'plan-gallery '+layout}>{group.sheets.map(s=><article className="plan-card" key={s.id}><button className="plan-card-preview" onClick={()=>onOpen(s)} aria-label={'Open '+s.code+' '+s.name}><PlanPreview sheet={s} projectId={project.id} headers={headers}/><span className="plan-open-badge">Open plan <ArrowUpRight size={16}/></span></button><div className="plan-card-footer"><button onClick={()=>onOpen(s)}><strong>{s.code}</strong><h2>{s.name}</h2><span>{s.revision} · {tasks.filter(t=>t.sheetId===s.id&&t.status!=='done').length} open tasks</span></button><div className="plan-card-controls">{canOrganize&&folders.length>0&&<label className="plan-folder-select"><FolderOpen size={14}/><Choice label={'Folder for '+s.code} value={s.folderId||'unfiled'} disabled={busy===s.id} options={folderOptions} onChange={async folderId=>{setBusy(s.id);try{await onMove(s,folderId==='unfiled'?'':folderId)}catch(e:any){toast.error(e.message)}finally{setBusy('')}}}/></label>}{s.audience?.length?(canManage?<label className="plan-audience"><Users size={15}/><AudienceSelect label={'Visibility for '+s.code} value={s.audience} disabled={busy===s.id} onChange={async a=>{setBusy(s.id);try{await onAudience(s,a)}finally{setBusy('')}}}/></label>:<span className="plan-access-label"><LockKeyhole size={14}/> {s.audience.join(', ')}</span>):null}</div></div></article>)}</div>{!group.sheets.length&&folders.length>0&&<div className="empty-folder"><p>No plans in this folder yet.</p>{canUpload&&<button className="text-button" onClick={()=>onUpload(group.id==='unfiled'?undefined:group.id)}>Import PDF here</button>}</div>}</>}</section>)}
 {!shown.length&&(!folders.length||query)&&<div className="overview-empty"><FolderOpen size={35}/><h2>{query?'No matching plans':'No plans yet'}</h2><p>{query?'Try a plan name or drawing number.':'Create discipline folders or import a PDF to begin.'}</p>{canUpload&&!query&&<button className="button outline" onClick={()=>onUpload()}>Import PDF</button>}</div>}
 <Dialog open={folderOpen} onOpenChange={v=>{if(busy!=='folder')setFolderOpen(v)}}><DialogContent className="folder-dialog"><DialogHeader><DialogTitle>{editingFolder?'Rename folder':'New plan folder'}</DialogTitle><DialogDescription>Use disciplines or any grouping that suits this project.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy('folder');try{await onFolder(editingFolder?'rename':'create',folderName,editingFolder);setFolderOpen(false)}catch(e:any){toast.error(e.message)}finally{setBusy('')}}}><label>Folder name<input autoFocus required maxLength={80} placeholder="e.g. Architectural plans" value={folderName} onChange={e=>setFolderName(e.target.value)}/></label>{!editingFolder&&<div className="folder-suggestions">{['Architectural plans','Electrical plans','Mechanical plans'].map(name=><button className="small-chip" type="button" key={name} onClick={()=>setFolderName(name)}>{name}</button>)}</div>}<button className="button primary" disabled={busy==='folder'||!folderName.trim()}>{busy==='folder'?<LoaderCircle size={16} className="spin"/>:<FolderPlus size={16}/>} {editingFolder?'Save name':'Create folder'}</button></form></DialogContent></Dialog>
 </main>
}
