"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,FolderOpen,Grid2X2,Rows3,Search,Plus,Upload,LoaderCircle,Users,LockKeyhole} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Audience,Project,Sheet,Task} from '@/lib/review-types';
import PlanPreview from './plan-preview';
import {AudienceSelect} from './review-controls';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export function ProjectOverview({request,onOpen,onCreate,headers,guest,onAccount,refreshKey,canCreate}:{request:Requester;onOpen:(id:string)=>void;onCreate:()=>void;headers:Record<string,string>;guest:boolean;onAccount:()=>void;refreshKey:string;canCreate:boolean}){
 const [projects,setProjects]=useState<Project[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),api=useRef(request);api.current=request;
 useEffect(()=>{let live=true;setLoading(true);api.current('/api/projects').then(r=>{if(live){setProjects(r.projects);setError('')}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[refreshKey]);
 const shown=projects.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
 return <main className="overview-page"><div className="overview-heading"><div><span className="eyebrow">OCTAVA REVIEW</span><h1>Projects</h1><p>{projects.length} project{projects.length===1?'':'s'} in your workspace</p></div>{canCreate&&<button className="button primary" onClick={onCreate}><Plus size={17}/> New project</button>}</div>
 <div className="overview-toolbar"><label className="searchbox"><Search size={17}/><input aria-label="Search projects" placeholder="Search projects" value={query} onChange={e=>setQuery(e.target.value)}/></label>{guest&&<button className="account-nudge" onClick={onAccount}>Save your workspace to an account <ArrowUpRight size={15}/></button>}</div>
 {error&&<div className="error-banner">{error}</div>}{loading?<div className="overview-loading"><LoaderCircle className="spin"/> Opening projects</div>:<div className="project-grid">{shown.map(p=><button className="project-card" key={p.id} onClick={()=>onOpen(p.id)}><div className="project-cover"><PlanPreview sheet={p.cover} projectId={p.id} headers={headers}/><span className="project-open-icon"><ArrowUpRight size={20}/></span></div><div className="project-card-body"><h2>{p.name}</h2><div><span>{p.planCount||0} plans</span><span>{p.taskCount||0} open tasks</span><span>{p.role==='owner'?'Administrator':p.role==='editor'?'Team':'Review'}</span></div></div></button>)}</div>}
 {!loading&&!shown.length&&<div className="overview-empty"><FolderOpen size={35}/><h2>{query?'No matching projects':'Your next project starts here'}</h2><p>{query?'Try another project name.':'Create a project and import its plans.'}</p>{!query&&canCreate&&<button className="button outline" onClick={onCreate}><Plus size={16}/> Create project</button>}</div>}
 </main>
}
export function PlanOverview({project,sheets,tasks,headers,onOpen,onUpload,canUpload,canManage,onAudience}:{project:Project;sheets:Sheet[];tasks:Task[];headers:Record<string,string>;onOpen:(s:Sheet)=>void;onUpload:()=>void;canUpload:boolean;canManage:boolean;onAudience:(s:Sheet,a:Audience)=>Promise<void>}){
 const [query,setQuery]=useState(''),[layout,setLayout]=useState('tiles'),[sort,setSort]=useState('code'),[busy,setBusy]=useState('');
 useEffect(()=>{try{const value=localStorage.getItem('octava.plan-layout');if(value==='rows'||value==='tiles')setLayout(value)}catch{}},[]);
 const shown=sheets.filter(s=>(s.name+' '+s.code+' '+s.revision).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='recent'?b.created.localeCompare(a.created):a.code.localeCompare(b.code,undefined,{numeric:true}));
 return <main className="overview-page plans-overview"><div className="overview-heading"><div><span className="eyebrow">{project.name}</span><h1>Plans</h1><p>{sheets.length} current plan{sheets.length===1?'':'s'}</p></div>{canUpload&&<button className="button primary" onClick={onUpload}><Upload size={17}/> Import PDF</button>}</div>
 <div className="overview-toolbar"><label className="searchbox"><Search size={17}/><input aria-label="Search plans" placeholder="Search plan name, number or revision" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="sort-label">Sort <select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort plans"><option value="code">Plan number</option><option value="recent">Newest first</option></select></label><Tabs value={layout} onValueChange={v=>{setLayout(v);try{localStorage.setItem('octava.plan-layout',v)}catch{}}}><TabsList className="layout-switch"><TabsTrigger value="tiles" aria-label="Small plan tiles"><Grid2X2 size={17}/></TabsTrigger><TabsTrigger value="rows" aria-label="Full width plans"><Rows3 size={17}/></TabsTrigger></TabsList></Tabs></div>
 <div className={'plan-gallery '+layout}>{shown.map(s=><article className="plan-card" key={s.id}><button className="plan-card-preview" onClick={()=>onOpen(s)} aria-label={'Open '+s.code+' '+s.name}><PlanPreview sheet={s} projectId={project.id} headers={headers}/><span className="plan-open-badge">Open plan <ArrowUpRight size={16}/></span></button><div className="plan-card-footer"><button onClick={()=>onOpen(s)}><strong>{s.code}</strong><h2>{s.name}</h2><span>{s.revision} · {tasks.filter(t=>t.sheetId===s.id&&t.status!=='done').length} open tasks</span></button>{canManage?<label className="plan-audience"><Users size={15}/><AudienceSelect label={'Visibility for '+s.code} value={s.audience} disabled={busy===s.id} onChange={async a=>{setBusy(s.id);try{await onAudience(s,a)}finally{setBusy('')}}}/></label>:s.audience?.length?<span className="plan-access-label"><LockKeyhole size={14}/> {s.audience.join(', ')}</span>:null}</div></article>)}</div>
 {!shown.length&&<div className="overview-empty"><FolderOpen size={35}/><h2>{query?'No matching plans':'No plans yet'}</h2><p>{query?'Try a plan name or drawing number.':'Import a PDF to begin the review.'}</p>{canUpload&&!query&&<button className="button outline" onClick={onUpload}>Import PDF</button>}</div>}
 </main>
}
