"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Camera,Download,FileText,Heart,Image as ImageIcon,LoaderCircle,Paperclip,Search,Upload} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import type {ProjectAsset} from '@/lib/review-types';
import {professionNames} from '@/lib/review-types';
import {photoSections} from './project-sidebar';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
const sizeLabel=(n:number)=>n>1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';
const assetPath=(projectId:string,file:ProjectAsset)=>'/api/'+(file.source==='task'?'attachments':'documents')+'?project='+encodeURIComponent(projectId)+'&id='+encodeURIComponent(file.id);
function AssetPreview({file,projectId,headers,large=false}:{file:ProjectAsset;projectId:string;headers:Record<string,string>;large?:boolean}){
 const [src,setSrc]=useState(''),[error,setError]=useState(false);
 useEffect(()=>{let live=true,url='';const controller=new AbortController();fetch(assetPath(projectId,file),{headers,signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Preview unavailable');const blob=await r.blob();if(live){url=URL.createObjectURL(blob);setSrc(url)}}).catch(()=>live&&setError(true));return()=>{live=false;controller.abort();if(url)URL.revokeObjectURL(url)}},[file.id,projectId]);
 if(error)return <div className="asset-preview-placeholder"><ImageIcon size={26}/><span>Preview unavailable · download original</span></div>;
 if(!src)return <div className="asset-preview-placeholder"><LoaderCircle className="spin" size={22}/></div>;
 if(file.mime.startsWith('image/'))return <img src={src} alt={file.name} loading="lazy" onError={()=>setError(true)} className={large?'asset-image-large':'asset-image'}/>;
 return <iframe title={file.name} src={src} className="asset-pdf-preview"/>;
}
export default function ProjectAssets({projectId,projectName,section,photoFilter,onPhotoFilter,headers,request,role,onTask}:{projectId:string;projectName:string;section:'photos'|'files'|'specifications';photoFilter:string;onPhotoFilter:(v:string)=>void;headers:Record<string,string>;request:Requester;role:string;onTask:(id:string)=>void}){
 const [assets,setAssets]=useState<ProjectAsset[]>([]),[userId,setUserId]=useState(''),[canUpload,setCanUpload]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(''),[selected,setSelected]=useState<ProjectAsset|null>(null),[liking,setLiking]=useState(new Set<string>());
 const api=useRef(request),input=useRef<HTMLInputElement>(null),likeWrites=useRef(new Set<string>()),sequence=useRef(0);api.current=request;
 useEffect(()=>{let live=true,busy=false;setLoading(true);setAssets([]);setQuery('');setSelected(null);const refresh=async()=>{if(busy)return;busy=true;const seq=sequence.current;try{const r=await api.current('/api/documents?project='+projectId,{signal:AbortSignal.timeout(12000)});if(live){if(seq===sequence.current&&!likeWrites.current.size){setAssets(r.assets);setSelected(old=>old?r.assets.find((f:ProjectAsset)=>f.id===old.id)||null:null)}setUserId(r.userId);setCanUpload(r.canUpload);setError('')}}catch(e:any){if(live)setError(e.message)}finally{busy=false;if(live)setLoading(false)}};const resume=()=>{if(!document.hidden)void refresh()};void refresh();const timer=setInterval(resume,3000);window.addEventListener('focus',resume);window.addEventListener('online',resume);document.addEventListener('visibilitychange',resume);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',resume);window.removeEventListener('online',resume);document.removeEventListener('visibilitychange',resume)}},[projectId]);
 const kind=section==='photos'?'photo':section==='specifications'?'specification':'file',matching=assets.filter(f=>f.kind===kind&&(section!=='photos'||photoFilter==='all'||photoFilter==='mine'&&f.creatorId===userId||photoFilter==='liked'&&f.liked)&&(!query||(f.name+' '+f.author).toLowerCase().includes(query.toLowerCase()))),title=section==='photos'?'Photos':section==='files'?'Files':'Specifications';
 async function like(file:ProjectAsset){if(likeWrites.current.has(file.id))return;likeWrites.current.add(file.id);setLiking(new Set(likeWrites.current));sequence.current++;try{const r=await request('/api/documents',{method:'PATCH',body:JSON.stringify({projectId,id:file.id,liked:!file.liked})});setAssets(old=>old.map(f=>f.id===file.id?{...f,...r}:f));setSelected(old=>old?.id===file.id?{...old,...r}:old)}catch(e:any){toast.error(e.message)}finally{sequence.current++;likeWrites.current.delete(file.id);setLiking(new Set(likeWrites.current))}}
 async function upload(files:File[]){if(!files.length)return;setUploading(true);let saved=0;try{for(const file of files){setProgress('Uploading '+(saved+1)+' of '+files.length);const form=new FormData();form.append('file',file);form.append('kind',kind);const r=await request('/api/documents?project='+projectId,{method:'POST',body:form});sequence.current++;setAssets(old=>[r.asset,...old]);saved++}toast.success(saved+' '+(kind==='photo'?'photo':'document')+(saved===1?'':'s')+' uploaded')}catch(e:any){toast.error((saved?saved+' saved. ':'')+e.message)}finally{setUploading(false);setProgress('');if(input.current)input.current.value=''}}
 async function download(file:ProjectAsset){try{const r=await fetch(assetPath(projectId,file)+'&download=1',{headers});if(!r.ok)throw Error('This file could not be downloaded.');const url=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){toast.error(e.message)}}
 return <main className="overview-page assets-page"><div className="overview-heading"><div><span className="eyebrow">{projectName}</span><h1>{title}</h1><p>{section==='photos'?'Site photos and images from task conversations':section==='files'?'Project documents and task attachments':'Project specification PDFs'}</p></div>{canUpload&&(section!=='specifications'||role!=='client')&&<button className="button primary" disabled={uploading} onClick={()=>input.current?.click()}>{uploading?<LoaderCircle className="spin" size={17}/>:<Upload size={17}/>} {uploading?progress:section==='photos'?'Add photos':'Upload '+(section==='files'?'files':'PDF')}</button>}<input ref={input} type="file" hidden multiple aria-label={'Upload '+title.toLowerCase()} accept={section==='photos'?'image/*':section==='specifications'?'application/pdf,.pdf':undefined} onChange={e=>upload(Array.from(e.target.files||[]))}/></div>
 <div className="overview-toolbar"><label className="searchbox"><Search size={16}/><input aria-label={'Search '+title.toLowerCase()} placeholder={'Search '+title.toLowerCase()} value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="asset-result-count">{matching.length} {section==='photos'?(matching.length===1?'photo':'photos'):(matching.length===1?'document':'documents')}</span></div>
 {section==='photos'&&<div className="photo-filters" aria-label="Photo collections">{photoSections.map(f=><button className={photoFilter===f.id?'active':''} key={f.id} aria-pressed={photoFilter===f.id} onClick={()=>onPhotoFilter(f.id)}><f.icon size={14}/>{f.label}</button>)}</div>}
 {error&&<div className="error-banner">{error}</div>}{loading?<div className="overview-loading"><LoaderCircle className="spin"/> Loading {title.toLowerCase()}</div>:<div className={section==='photos'?'photo-grid':'document-list'}>{matching.map(file=><article key={file.id} className={section==='photos'?'photo-card':'document-row'}>{section==='photos'?<><button className="photo-preview" onClick={()=>setSelected(file)}><AssetPreview file={file} projectId={projectId} headers={headers}/></button><div className="photo-card-caption"><div><strong>{file.name}</strong><small>{file.author} · {professionNames[file.authorRole]}</small></div><button className={'photo-like '+(file.liked?'liked':'')} disabled={liking.has(file.id)} aria-label={(file.liked?'Unlike ':'Like ')+file.name} aria-pressed={file.liked} onClick={()=>like(file)}><Heart size={18} fill={file.liked?'currentColor':'none'}/><span>{file.likeCount||''}</span></button></div></>:<><span className="document-icon">{section==='specifications'?<BookOpen size={23}/>:<FileText size={23}/>}</span><button className="document-name" onClick={()=>file.mime==='application/pdf'?setSelected(file):download(file)}><strong>{file.name}</strong><small>{sizeLabel(file.size)} · {file.author} · {new Date(file.created).toLocaleDateString()}</small></button>{file.taskId&&<button className="icon-button" title="Open task" aria-label={'Open task for '+file.name} onClick={()=>onTask(file.taskId!)}><ArrowUpRight size={17}/></button>}<button className="icon-button" aria-label={'Download '+file.name} onClick={()=>download(file)}><Download size={17}/></button></>}</article>)}</div>}
 {!loading&&!matching.length&&<div className="overview-empty">{section==='photos'?<Camera size={34}/>:section==='specifications'?<BookOpen size={34}/>:<Paperclip size={34}/>}<h2>{query?'No matching '+title.toLowerCase():section==='photos'&&photoFilter==='liked'?'Your liked photos appear here':'No '+title.toLowerCase()+' yet'}</h2><p>{section==='photos'&&photoFilter==='liked'?'Tap the heart on a photo to save it to this collection.':section==='photos'&&photoFilter==='mine'?'Photos you upload here or add to tasks appear here.':'Upload a file to keep it with this project.'}</p></div>}
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="project-asset-dialog"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.author}{selected?' · '+sizeLabel(selected.size):''}</DialogDescription></DialogHeader>{selected&&<><AssetPreview file={selected} projectId={projectId} headers={headers} large/><div className="asset-detail-actions">{selected.kind==='photo'&&<button className={'button outline '+(selected.liked?'photo-liked':'')} disabled={liking.has(selected.id)} onClick={()=>like(selected)}><Heart size={16} fill={selected.liked?'currentColor':'none'}/>{selected.liked?'Liked':'Like'} · {selected.likeCount}</button>}{selected.taskId&&<button className="button outline" onClick={()=>{onTask(selected.taskId!);setSelected(null)}}>Open task <ArrowUpRight size={15}/></button>}<button className="button outline" onClick={()=>download(selected)}><Download size={16}/> Download</button></div></>}</DialogContent></Dialog>
 </main>
}
