"use client";
import {flushOpenDrawings} from '@/lib/document-drawings';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Camera,CheckSquare,Download,FileText,Folder,FolderPlus,Heart,LoaderCircle,Paperclip,Pencil,Presentation,Search,Trash2,Upload} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import type {PhotoGroup,ProjectAsset} from '@/lib/review-types';
import {professionNames} from '@/lib/review-types';
import {uploadFile,uploadThumbnail,type Requester} from '@/lib/upload-client';
import {photoSections,type PhotoNavigation} from './project-sidebar';
import {Choice} from './review-controls';
import AssetPreview,{assetPath} from './asset-preview';
import ProjectBackups from './project-backups';
const sizeLabel=(n:number)=>n>1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';
type Section='photos'|'files'|'specifications'|'presentations';
export default function ProjectAssets({projectId,projectName,section,photoFilter,onPhotoFilter,group,onGroup,onPhotoNavigation,createGroupOpen,onCreateGroupOpenChange,headers,request,role,onTask}:{projectId:string;projectName:string;section:Section;photoFilter:string;onPhotoFilter:(v:string)=>void;group:string;onGroup:(v:string)=>void;onPhotoNavigation:(v:PhotoNavigation)=>void;createGroupOpen:boolean;onCreateGroupOpenChange:(v:boolean)=>void;headers:Record<string,string>;request:Requester;role:string;onTask:(id:string)=>void}){
 const [assets,setAssets]=useState<ProjectAsset[]>([]),[groups,setGroups]=useState<PhotoGroup[]>([]),[userId,setUserId]=useState(''),[canUpload,setCanUpload]=useState(false),[canOrganize,setCanOrganize]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(''),[selected,setSelected]=useState<ProjectAsset|null>(null),[liking,setLiking]=useState(new Set<string>()),[selection,setSelection]=useState(new Set<string>()),[selecting,setSelecting]=useState(false),[page,setPage]=useState(0),[moving,setMoving]=useState(false);
 const [localEdit,setEdit]=useState<{kind:'group'|'renameGroup'|'removeGroup'|'document'|'presentation';id?:string}|null>(null),[editName,setEditName]=useState(''),[editing,setEditing]=useState(false),[pendingFiles,setPendingFiles]=useState<File[]>([]);
 const edit=createGroupOpen?{kind:'group' as const}:localEdit;
 function closeEdit(){setEdit(null);onCreateGroupOpenChange(false)}
 useEffect(()=>{if(createGroupOpen)setEditName('')},[createGroupOpen]);
 useEffect(()=>{if(section==='photos')onPhotoNavigation({projectId,groups:groups.map(g=>({...g,count:assets.filter(f=>f.kind==='photo'&&f.groupId===g.id).length})),ungroupedCount:assets.filter(f=>f.kind==='photo'&&!f.groupId).length,canOrganize})},[projectId,section,groups,assets,canOrganize,onPhotoNavigation]);
 const api=useRef(request),input=useRef<HTMLInputElement>(null),writes=useRef(0),sequence=useRef(0),likeWrites=useRef(new Set<string>());api.current=request;
 async function refresh(){const r=await api.current('/api/documents?project='+projectId);setAssets(r.assets);setGroups(r.groups||[]);return r}
 useEffect(()=>{
  let live=true,busy=false;setLoading(true);const load=async()=>{if(busy||writes.current)return;busy=true;const seq=sequence.current;try{const r=await api.current('/api/documents?project='+projectId,{signal:AbortSignal.timeout(15000)});if(live){if(seq===sequence.current&&!writes.current){setAssets(r.assets);setGroups(r.groups||[]);setSelected(old=>old?r.assets.find((f:ProjectAsset)=>f.id===old.id)||null:null)}setUserId(r.userId);setCanUpload(r.canUpload);setCanOrganize(r.canOrganize);setError('')}}catch(e:any){if(live)setError(e.message)}finally{busy=false;if(live)setLoading(false)}};
  const resume=()=>{if(!document.hidden)void load()};void load();const timer=setInterval(resume,5000);window.addEventListener('focus',resume);window.addEventListener('online',resume);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',resume);window.removeEventListener('online',resume)};
 },[projectId]);
 useEffect(()=>{if(!loading&&!error&&section==='photos'&&!['all','ungrouped'].includes(group)&&!groups.some(g=>g.id===group))onGroup('all')},[loading,error,section,group,groups,onGroup]);
 useEffect(()=>{setPage(0);setSelection(new Set())},[group,query,photoFilter]);
 const kind=section==='photos'?'photo':section==='specifications'?'specification':section==='presentations'?'presentation':'file',title=section[0].toUpperCase()+section.slice(1);
 const matching=assets.filter(f=>f.kind===kind&&(section!=='photos'||(photoFilter==='all'||photoFilter==='mine'&&f.creatorId===userId||photoFilter==='liked'&&f.liked)&&(group==='all'||group==='ungrouped'&&!f.groupId||f.groupId===group))&&(!query||(f.name+' '+f.author).toLowerCase().includes(query.toLowerCase())));
 const pages=Math.max(1,Math.ceil(matching.length/36)),shown=matching.slice(Math.min(page,pages-1)*36,(Math.min(page,pages-1)+1)*36),activeGroup=groups.find(g=>g.id===group);
 async function like(file:ProjectAsset){if(likeWrites.current.has(file.id))return;likeWrites.current.add(file.id);setLiking(new Set(likeWrites.current));writes.current++;sequence.current++;try{const r=await request('/api/documents',{method:'PATCH',body:JSON.stringify({projectId,id:file.id,liked:!file.liked})});setAssets(old=>old.map(f=>f.id===file.id?{...f,...r}:f));setSelected(old=>old?.id===file.id?{...old,...r}:old)}catch(e:any){toast.error(e.message)}finally{writes.current--;sequence.current++;likeWrites.current.delete(file.id);setLiking(new Set(likeWrites.current))}}
 async function upload(files:File[],presentationName?:string){if(!files.length)return;setUploading(true);writes.current++;let saved=0;try{for(const file of files){const r=await uploadFile(request,projectId,file,'document',{kind,groupId:section==='photos'&&activeGroup?activeGroup.id:undefined,name:kind==='presentation'?presentationName+(saved?' '+(saved+1):''):undefined},n=>setProgress('File '+(saved+1)+' of '+files.length+' · '+n+'%'));sequence.current++;setAssets(old=>[r.asset,...old.filter(f=>f.id!==r.asset.id)]);saved++;if(kind==='photo')await uploadThumbnail(request,projectId,r.asset.id,file).catch(()=>false)}toast.success(saved+' '+(kind==='photo'?'photo':'document')+(saved===1?'':'s')+' uploaded');setEdit(null);setPendingFiles([])}catch(e:any){setPendingFiles(files.slice(saved));toast.error((saved?saved+' saved. ':'')+e.message)}finally{writes.current--;sequence.current++;setUploading(false);setProgress('');if(input.current)input.current.value=''}}
 function choose(files:File[]){if(!files.length)return;if(section==='presentations'){const d=new Date();setEditName(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+' '+projectName);setPendingFiles(files);setEdit({kind:'presentation'})}else void upload(files)}
 async function download(file:ProjectAsset){try{const r=await fetch(assetPath(projectId,file)+'&download=1',{headers});if(!r.ok)throw Error('This file could not be downloaded.');const url=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){toast.error(e.message)}}
 async function saveEdit(e:React.FormEvent){e.preventDefault();if(!edit)return;if(edit.kind==='presentation'){await upload(pendingFiles,editName);return}setEditing(true);writes.current++;try{if(edit.kind==='document')await request('/api/documents',{method:'PATCH',body:JSON.stringify({projectId,id:edit.id,name:editName})});else {const r=await request('/api/photo-groups',{method:'POST',body:JSON.stringify({projectId,action:edit.kind==='group'?'create':edit.kind==='renameGroup'?'rename':'remove',id:edit.id,name:edit.kind==='removeGroup'?undefined:editName})});setGroups(r.groups);if(edit.kind==='removeGroup')onGroup('all');if(edit.kind==='group'){const created=r.groups.find((g:PhotoGroup)=>g.name===editName.trim());if(created)onGroup(created.id)}}await refresh();sequence.current++;closeEdit();toast.success(edit.kind==='removeGroup'?'Group removed. Photos kept.':'Saved')}catch(e:any){toast.error(e.message)}finally{writes.current--;setEditing(false)}}
 function togglePhoto(id:string){setSelection(old=>{const next=new Set(old);if(next.has(id))next.delete(id);else next.add(id);return next})}
 async function move(groupId:string,ids:string[]=[...selection]){if(!ids.length||moving||groupId==='choose')return;setMoving(true);writes.current++;try{await request('/api/photo-groups',{method:'POST',body:JSON.stringify({projectId,action:'move',photoIds:ids,groupId:groupId==='ungrouped'?null:groupId})});const result=await refresh();setSelected(old=>old?result.assets.find((f:ProjectAsset)=>f.id===old.id)||null:null);sequence.current++;setSelection(new Set());toast.success(groupId==='ungrouped'?'Photos removed from group':'Photos assigned to '+(groups.find(g=>g.id===groupId)?.name||'group'))}catch(e:any){toast.error(e.message)}finally{writes.current--;setMoving(false)}}

 return <main className="overview-page assets-page">
  <div className="overview-heading"><div><span className="eyebrow">{projectName}</span><h1>{section==='photos'?(activeGroup?.name||(group==='ungrouped'?'Ungrouped photos':title)):title}</h1><p>{section==='photos'?'Project photos and task images':section==='presentations'?'PDF previews · PowerPoint and Keynote downloads':section==='files'?'Project documents and task attachments':'Project specification PDFs'}</p></div><div className="overview-heading-actions">{section==='files'&&role==='owner'&&<ProjectBackups projectId={projectId} request={request}/>}{section==='photos'&&canOrganize&&<button className="button outline photo-new-group" onClick={()=>onCreateGroupOpenChange(true)}><FolderPlus size={16}/> New group</button>}{canUpload&&(!['specifications','presentations'].includes(section)||role!=='client')&&<button className="button primary" disabled={uploading} onClick={()=>input.current?.click()}>{uploading?<LoaderCircle className="spin" size={17}/>:<Upload size={17}/>} {uploading?progress:section==='photos'?'Add photos':'Upload'}</button>}</div><input ref={input} type="file" hidden multiple aria-label={'Upload '+title.toLowerCase()} accept={section==='photos'?'image/*':section==='specifications'?'application/pdf,.pdf':section==='presentations'?'.pdf,.ppt,.pptx,.key':undefined} onChange={e=>choose(Array.from(e.target.files||[]))}/></div>
  <div className="overview-toolbar"><label className="searchbox"><Search size={16}/><input aria-label={'Search '+title.toLowerCase()} placeholder={'Search '+title.toLowerCase()} value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="asset-result-count">{matching.length} {section==='photos'?'photos':'documents'}</span></div>
  {section==='photos'&&<><div className="photo-filters" aria-label="Photo collections">{photoSections.map(f=><button className={photoFilter===f.id?'active':''} key={f.id} aria-pressed={photoFilter===f.id} onClick={()=>onPhotoFilter(f.id)}><f.icon size={14}/>{f.label}</button>)}</div><div className="photo-group-toolbar"><div className="mobile-photo-group-picker"><Choice label="Photo group" value={group} onChange={onGroup} options={[{value:'all',label:'All groups'},{value:'ungrouped',label:'Ungrouped photos'},...groups.map(g=>({value:g.id,label:g.name}))]}/></div>{activeGroup&&canOrganize&&<><button className="icon-button" aria-label="Rename photo group" onClick={()=>{setEditName(activeGroup.name);setEdit({kind:'renameGroup',id:group})}}><Pencil size={16}/></button><button className="icon-button" aria-label="Remove photo group" onClick={()=>setEdit({kind:'removeGroup',id:group})}><Trash2 size={16}/></button></>}{canOrganize&&<button className="button outline" aria-pressed={selecting} onClick={()=>{setSelecting(v=>!v);setSelection(new Set())}}><CheckSquare size={16}/>{selecting?'Done':'Select photos'}</button>}</div>{selecting&&<div className="photo-selection-bar"><span>{selection.size} selected</span><button className="text-button" onClick={()=>setSelection(new Set(shown.map(f=>f.id)))}>Select this page</button>{selection.size>0&&<Choice label="Assign selected photos to group" value="choose" disabled={moving} onChange={v=>void move(v)} options={[{value:'choose',label:moving?'Moving…':'Assign to group…'},{value:'ungrouped',label:'Ungrouped photos'},...groups.map(g=>({value:g.id,label:g.name}))]}/>}</div>}</>}
  {error&&<div className="error-banner">{error}</div>}{loading?<div className="overview-loading"><LoaderCircle className="spin"/> Loading {title.toLowerCase()}</div>:<div className={section==='photos'?'photo-grid':'document-list'}>{shown.map(file=><article key={file.id} className={section==='photos'?'photo-card '+(selection.has(file.id)?'is-selected':''):'document-row'}>{section==='photos'?<>{selecting&&<label className="photo-selection"><Checkbox aria-label={'Select '+file.name} checked={selection.has(file.id)} onCheckedChange={()=>togglePhoto(file.id)}/></label>}<button className="photo-preview" aria-label={(selecting?'Select ':'Open ')+file.name} aria-pressed={selecting?selection.has(file.id):undefined} onClick={()=>selecting?togglePhoto(file.id):setSelected(file)}><AssetPreview file={file} projectId={projectId} headers={headers}/></button><div className="photo-card-caption"><div><strong>{file.name}</strong><small>{file.author} · {professionNames[file.authorRole]}</small>{file.groupId&&<small>{groups.find(g=>g.id===file.groupId)?.name}</small>}</div>{canOrganize&&!selecting&&<button className="icon-button photo-assign-button" aria-label={'Assign '+file.name+' to group'} title="Assign to group" onClick={()=>setSelected(file)}><Folder size={17}/></button>}<button className={'photo-like '+(file.liked?'liked':'')} disabled={liking.has(file.id)} aria-label={(file.liked?'Unlike ':'Like ')+file.name} aria-pressed={file.liked} onClick={()=>like(file)}><Heart size={18} fill={file.liked?'currentColor':'none'}/><span>{file.likeCount||''}</span></button></div></>:<><span className="document-icon">{section==='specifications'?<BookOpen size={23}/>:section==='presentations'?<Presentation size={23}/>:<FileText size={23}/>}</span><button className="document-name" onClick={()=>file.mime==='application/pdf'?setSelected(file):download(file)}><strong>{file.name}</strong><small>{sizeLabel(file.size)} · {file.author} · {new Date(file.created).toLocaleDateString()}</small></button>{file.source==='project'&&canOrganize&&<button className="icon-button" aria-label={'Rename '+file.name} onClick={()=>{setEditName(file.name.replace(/\.[a-z0-9]{1,8}$/i,''));setEdit({kind:'document',id:file.id})}}><Pencil size={16}/></button>}{file.taskId&&<button className="icon-button" aria-label={'Open task for '+file.name} onClick={()=>onTask(file.taskId!)}><ArrowUpRight size={17}/></button>}<button className="icon-button" aria-label={'Download '+file.name} onClick={()=>download(file)}><Download size={17}/></button></>}</article>)}</div>}
  {!loading&&!matching.length&&<div className="overview-empty">{section==='photos'?<Camera size={34}/>:section==='presentations'?<Presentation size={34}/>:<Paperclip size={34}/>}<h2>{query?'No matches':section==='photos'&&photoFilter==='liked'?'Your liked photos appear here':'No '+title.toLowerCase()+' here yet'}</h2><p>{section==='photos'&&photoFilter==='liked'?'Tap the heart on a photo to save it here.':activeGroup?'Upload photos here or select photos in another group and move them.':'Upload files up to 200 MB to keep them with this project.'}</p></div>}
  {pages>1&&<div className="asset-pagination"><button className="button outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {Math.min(page,pages-1)+1} of {pages}</span><button className="button outline" disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}>Next</button></div>}
  <Dialog open={!!selected} onOpenChange={async v=>{if(!v&&(selected?.mime!=='application/pdf'||await flushOpenDrawings()))setSelected(null)}}><DialogContent className="project-asset-dialog"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.author}{selected?' · '+sizeLabel(selected.size):''}</DialogDescription></DialogHeader>{selected&&<><AssetPreview file={selected} projectId={projectId} headers={headers} large/><div className="asset-detail-actions">{selected.kind==='photo'&&canOrganize&&<div className="asset-group-assignment"><label>Photo group</label><Choice label="Assign photo to group" value={selected.groupId||'ungrouped'} disabled={moving} onChange={v=>void move(v,[selected.id])} options={[{value:'ungrouped',label:'Ungrouped'},...groups.map(g=>({value:g.id,label:g.name}))]}/></div>}{selected.kind==='photo'&&<button className={'button outline '+(selected.liked?'photo-liked':'')} disabled={liking.has(selected.id)} onClick={()=>like(selected)}><Heart size={16} fill={selected.liked?'currentColor':'none'}/>{selected.liked?'Liked':'Like'} · {selected.likeCount}</button>}{selected.taskId&&<button className="button outline" onClick={()=>{onTask(selected.taskId!);setSelected(null)}}>Open task <ArrowUpRight size={15}/></button>}<button className="button outline" onClick={()=>download(selected)}><Download size={16}/> Download original</button></div></>}</DialogContent></Dialog>
  <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!editing&&!uploading)closeEdit()}}><DialogContent className="asset-name-dialog"><DialogHeader><DialogTitle>{edit?.kind==='group'?'New photo group':edit?.kind==='renameGroup'?'Rename photo group':edit?.kind==='removeGroup'?'Remove this group?':edit?.kind==='presentation'?'Upload presentation':'Rename document'}</DialogTitle><DialogDescription>{edit?.kind==='removeGroup'?'The photos are kept and become ungrouped.':edit?.kind==='presentation'?'The date and project name are filled in. Change them here or rename the file later.':'Choose a clear name for your project.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={saveEdit}>{edit?.kind!=='removeGroup'&&<label>Name<input autoFocus required value={editName} maxLength={edit?.kind==='group'||edit?.kind==='renameGroup'?100:220} onChange={e=>setEditName(e.target.value)}/></label>}{edit?.kind==='presentation'&&<p className="form-note">{pendingFiles.length} file{pendingFiles.length===1?'':'s'} · up to 200 MB each</p>}<button className="button primary" disabled={editing||uploading}>{editing||uploading?<><LoaderCircle className="spin" size={16}/>{progress||'Saving…'}</>:edit?.kind==='removeGroup'?'Remove group':edit?.kind==='presentation'?'Upload presentation':'Save'}</button></form></DialogContent></Dialog>
 </main>
}
