"use client";
import {useState} from 'react';
import {Archive,Download,LoaderCircle,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import type {Requester} from '@/lib/upload-client';
export default function ProjectBackups({projectId,request}:{projectId:string;request:Requester}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[restored,setRestored]=useState(''),[confirm,setConfirm]=useState('');
 async function refresh(){const r=await request('/api/backups?project='+projectId);setRows(r.backups)}
 async function show(){setOpen(true);setError('');try{await refresh()}catch(e:any){setError(e.message)}}
 async function run(action:'create'|'step'|'restore',id?:string){if(busy)return;setBusy(true);setError('');setRestored('');setConfirm('');setProgress(action==='restore'?'Preparing restored copy…':'Saving project snapshot…');try{
  let r=await request('/api/backups',{method:'POST',body:JSON.stringify({projectId,action,id})});const restore=action==='restore',jobId=r.id;
  while(r.status!=='ready'){setProgress((restore?'Restoring':'Backing up')+' files · '+r.cursor+' of '+r.total);r=await request('/api/backups',{method:'POST',body:JSON.stringify({projectId,action:restore?'restoreStep':'step',id:jobId})})}
  if(restore){setRestored(r.projectId);toast.success('Restored as a separate, private project')}else toast.success('Backup complete');await refresh();
 }catch(e:any){setError(e.message+' You can resume without starting again.')}finally{setBusy(false);setProgress('')}}
 return <><button className="button outline" onClick={show}><Archive size={16}/> Backups</button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="backup-dialog"><DialogHeader><DialogTitle>Project backups</DialogTitle><DialogDescription>Manual snapshots of plans, annotations, tasks, conversations and original files. Keep a downloaded copy outside the app as well.</DialogDescription></DialogHeader><button className="button primary" disabled={busy} onClick={()=>run('create')}>{busy?<LoaderCircle className="spin" size={16}/>:<Archive size={16}/>} {busy?progress:'Create backup now'}</button><p className="form-note">Keep this window open until copying finishes. A restore creates a separate project and does not reactivate sharing links or participant access. Backups use additional storage.</p>{error&&<p className="form-error" role="alert">{error}</p>}{restored&&<a className="button primary" href={'/?project='+restored}>Open restored project</a>}<div className="backup-list">{rows.map(row=><div className="backup-row" key={row.id}><div><strong>{new Date(row.created).toLocaleString()}</strong><small>{row.status==='ready'?'Complete · '+row.total+' original files':'Incomplete · '+row.cursor+' of '+row.total+' files'}</small></div>{row.status==='ready'?<><a className="icon-button" aria-label="Download backup archive" title="Download archive (.tar)" href={'/api/backups?project='+projectId+'&id='+row.id}><Download size={17}/></a><button className="button outline" disabled={busy} onClick={()=>setConfirm(row.id)}><RotateCcw size={15}/> Restore copy</button></>:<button className="button outline" disabled={busy} onClick={()=>run('step',row.id)}>Resume</button>}</div>)}</div>{confirm&&<div className="backup-confirm"><p>Restore this snapshot into a new project? Your current project stays unchanged.</p><button className="button primary" disabled={busy} onClick={()=>run('restore',confirm)}>Restore separate copy</button><button className="button outline" onClick={()=>setConfirm('')}>Cancel</button></div>}</DialogContent></Dialog></>
}
