"use client";
import {ArrowLeft,BookOpen,Camera,CheckCheck,ChevronDown,ClipboardList,FolderOpen,Heart,HelpCircle,Layers,Paperclip,Presentation,UserRound,Users} from 'lucide-react';
import {Choice} from './review-controls';
import type {Project} from '@/lib/review-types';
export const projectSections=[{id:'plans',label:'Plans',icon:Layers},{id:'tasks',label:'Tasks',icon:ClipboardList},{id:'photos',label:'Photos',icon:Camera},{id:'presentations',label:'Presentations',icon:Presentation},{id:'files',label:'Files',icon:Paperclip},{id:'specifications',label:'Specifications',icon:BookOpen}];
export const photoSections=[{id:'all',label:'All photos',icon:Camera},{id:'mine',label:'My photos',icon:UserRound},{id:'liked',label:'Liked photos',icon:Heart}];
export default function ProjectSidebar({view,onView,projectId,projects,projectName,onProject,photoFilter,onPhotoFilter,onPeople,onAccount,onHelp,canManage,name,saved}:{view:string;onView:(v:string)=>void;projectId:string;projects:Project[];projectName:string;onProject:(id:string)=>void;photoFilter:string;onPhotoFilter:(v:string)=>void;onPeople:()=>void;onAccount:()=>void;onHelp:()=>void;canManage:boolean;name:string;saved:string}){
 const compact=view==='drawings';
 return <aside className={'project-sidebar '+(compact?'compact-sidebar':'')} aria-label="Project navigation"><div className="sidebar-project-switch"><span className="sidebar-project-symbol"><FolderOpen size={20}/></span>{projects.length?<Choice label="Sidebar project" value={projectId} onChange={onProject} options={projects.map(p=>({value:p.id,label:p.name}))}/>:<strong>{projectName||'Octava Review'}</strong>}</div><button className="sidebar-back-projects" onClick={()=>onView('projects')} title="All projects"><ArrowLeft size={15}/><span>All projects</span></button><span className="sidebar-section-label">PROJECT REVIEW</span><nav className="project-section-links">{projectSections.map(item=><button key={item.id} title={item.label} aria-label={item.label} aria-current={view===item.id||(item.id==='plans'&&compact)?'page':undefined} className={'project-nav-entry '+(view===item.id||(item.id==='plans'&&compact)?'active':'')} onClick={()=>onView(item.id)}><item.icon size={19}/><span>{item.label}</span></button>)}</nav>{view==='photos'&&<div className="sidebar-photo-links"><h2>Photos</h2>{photoSections.map(item=><button key={item.id} className={'project-nav-entry '+(photoFilter===item.id?'active':'')} onClick={()=>onPhotoFilter(item.id)}><item.icon size={17}/><span>{item.label}</span></button>)}</div>}<div className="project-sidebar-footer"><span className="sidebar-save-state" title={saved}><CheckCheck size={14}/><span>{saved}</span></span>{canManage&&<button className="project-nav-entry" onClick={onPeople} title="Project people"><Users size={18}/><span>People</span></button>}<button className="project-nav-entry" onClick={onAccount} title="Your account"><UserRound size={18}/><span>{name||'Your account'}</span></button><button className="project-nav-entry sidebar-help" onClick={onHelp} title="Keyboard shortcuts"><HelpCircle size={17}/><span>Shortcuts</span></button></div></aside>
}
