"use client";
import {flushOpenDrawings} from '@/lib/document-drawings';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Archive,BookOpen,Check,ChevronDown,Download,ExternalLink,FileText,Folder,FolderPlus,ImagePlus,Link2,LoaderCircle,Pencil,Plus,Search,Trash2,Upload,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Choice} from './review-controls';
import AssetPreview,{assetPath} from './asset-preview';
import {SpecificationEntryForm,SpecificationPaymentForm,SpecificationQuoteForm} from './specification-forms';
import {uid,type ProjectAsset} from '@/lib/review-types';
import {uploadFile,type Requester} from '@/lib/upload-client';
import UploadQueue from './upload-queue';
import {isPdf,newUploadItems,runUploadBatch,type UploadItem} from '@/lib/upload-batch';
import {directlyPurchased,quotePaid,selectedOffer,specMoney,specTotals,specificationStages,type Specification,type SpecGroup,type SpecNavigation,type SupplierQuote} from '@/lib/specifications';

type Props={projectId:string;projectName:string;headers:Record<string,string>;request:Requester;group:string;onGroup:(v:string)=>void;onNavigation:(navigation:SpecNavigation)=>void;createGroupOpen:boolean;onCreateGroupOpenChange:(v:boolean)=>void};
export default function Specifications({projectId,projectName,headers,request,group,onGroup,onNavigation,createGroupOpen,onCreateGroupOpenChange}:Props){
 const [uploadQueue,setUploadQueue]=useState<UploadItem[]>([]),[uploading,setUploading]=useState(false),uploadRunning=useRef(false);
 const [entries,setEntries]=useState<Specification[]>([]),[groups,setGroups]=useState<SpecGroup[]>([]),[assets,setAssets]=useState<ProjectAsset[]>([]),[canEdit,setCanEdit]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[openId,setOpenId]=useState<string|null>(null),[panel,setPanel]=useState('quotes'),[busy,setBusy]=useState(false),[documentsOpen,setDocumentsOpen]=useState(false),[preview,setPreview]=useState<ProjectAsset|null>(null);
 const [edit,setEdit]=useState<Specification|null>(null),[quoteEdit,setQuoteEdit]=useState<{entry:Specification;quote?:SupplierQuote}|null>(null),[paymentEdit,setPaymentEdit]=useState<Specification|null>(null),[groupEdit,setGroupEdit]=useState<SpecGroup|null>(null),[groupName,setGroupName]=useState(''),[groupError,setGroupError]=useState(''),[confirm,setConfirm]=useState<{group?:SpecGroup;entry?:Specification}|null>(null),[confirmError,setConfirmError]=useState('');
 const api=useRef(request),writes=useRef(0),sequence=useRef(0),input=useRef<HTMLInputElement>(null),alive=useRef(true);api.current=request;
 const load=useCallback(async()=>{const seq=sequence.current;const result=await api.current('/api/specifications?project='+encodeURIComponent(projectId),{signal:AbortSignal.timeout(15000)});if(alive.current&&seq===sequence.current&&!writes.current){setEntries(result.entries);setGroups(result.groups);setAssets(result.assets);setCanEdit(result.canEdit);setError('')}return result},[projectId]);
 useEffect(()=>{alive.current=true;let running=false;setLoading(true);const refresh=async()=>{if(running||writes.current||document.hidden)return;running=true;try{await load()}catch(e:any){if(alive.current)setError(e.message)}finally{running=false;if(alive.current)setLoading(false)}};void refresh();const timer=setInterval(refresh,5000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);return()=>{alive.current=false;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh)}},[load]);
 useEffect(()=>{onNavigation({projectId,groups:groups.map(g=>({...g,count:entries.filter(e=>!e.archived&&e.groupId===g.id).length})),canEdit,ungrouped:entries.filter(e=>!e.archived&&!e.groupId).length,archived:entries.filter(e=>e.archived).length})},[projectId,groups,entries,canEdit,onNavigation]);
 useEffect(()=>{if(createGroupOpen){setGroupName('');setGroupError('');setGroupEdit(null)}},[createGroupOpen]);
 useEffect(()=>{if(!loading&&!error&&!['all','ungrouped','archived'].includes(group)&&!groups.some(g=>g.id===group))onGroup('all')},[group,groups,loading,error,onGroup]);
 const onAsset=(asset:ProjectAsset)=>setAssets(old=>[asset,...old.filter(f=>f.id!==asset.id)]);
 const common={projectId,request,headers,assets,onAsset};
 const activeGroup=groups.find(g=>g.id===group),allActive=entries.filter(e=>!e.archived),totals=specTotals(entries),matching=entries.filter(e=>(group==='archived'?e.archived:!e.archived)&&(group==='all'||group==='archived'||group==='ungrouped'&&!e.groupId||e.groupId===group)&&(!query||[e.name,e.description,e.notes,...e.quotes.map(q=>q.provider)].join(' ').toLowerCase().includes(query.toLowerCase())));
 const sections=[...groups.map(g=>({id:g.id,name:g.name})),{id:'ungrouped',name:'Ungrouped'}].filter(g=>group==='all'||group==='archived'||group===g.id);
 const documents=assets.filter(f=>f.kind==='specification');
 function toggle(id:string,next:string){setOpenId(old=>old===id&&panel===next?null:id);setPanel(next)}
 async function saveEntry(entry:Specification){writes.current++;sequence.current++;setBusy(true);try{const r=await request('/api/specifications',{method:'POST',body:JSON.stringify({projectId,action:'save',entry})});setEntries(old=>old.some(e=>e.id===r.entry.id)?old.map(e=>e.id===r.entry.id?r.entry:e):[...old,r.entry]);setError('');toast.success('Specification saved');}finally{writes.current--;sequence.current++;setBusy(false)}}
 function update(entry:Specification,patch:Partial<Specification>){void saveEntry({...entry,...patch}).catch(e=>toast.error(e.message))}
 function newEntry(){const now=new Date().toISOString();setEdit({id:uid(),name:'',description:'',notes:'',groupId:activeGroup?.id||null,photoId:null,referenceId:null,stage:'Quoting',purchasedBy:'Studio',quotes:[],payments:[],selectedQuoteId:null,selectedRevisionId:null,priceSourceId:null,archived:false,version:0,created:now,updated:now})}
 function openFile(id:string|null){const file=assets.find(f=>f.id===id);if(!file){toast.error('This file is no longer available.');return}if(file.mime==='application/pdf'||file.mime.startsWith('image/'))setPreview(file);else void download(file)}
 async function download(file:ProjectAsset){try{const response=await fetch(assetPath(projectId,file)+'&download=1',{headers});if(!response.ok)throw Error('This file could not be downloaded.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){toast.error(e.message)}}
 useEffect(()=>{if(!uploading)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[uploading]);
 async function uploadDocuments(items:UploadItem[]){
  if(!items.length||uploadRunning.current)return;uploadRunning.current=true;setUploading(true);setBusy(true);writes.current++;sequence.current++;let saved=0;
  try{
   const queue=await runUploadBatch(items,async(item,progress)=>{if(!isPdf(item.file))throw Error('Choose a PDF file.');const result=await uploadFile(request,projectId,item.file,'document',{kind:'specification'},progress);onAsset(result.asset);saved++},setUploadQueue);
   if(saved){setDocumentsOpen(true);toast.success(saved+' specification PDF'+(saved===1?'':'s')+' uploaded')}
   if(queue.some(i=>i.status==='error'))toast.error('Some PDFs need attention. Retry them below.');
  }finally{writes.current--;sequence.current++;uploadRunning.current=false;setUploading(false);setBusy(false);if(input.current)input.current.value=''}
 }

 function offerPanel(entry:Specification){
  const current=selectedOffer(entry);
  return <div className="spec-quotes"><div className="spec-panel-heading"><span>{entry.quotes.length} supplier {entry.quotes.length===1?'quote':'quotes'}</span>{canEdit&&!entry.archived&&<button className="button outline" disabled={busy} onClick={()=>setQuoteEdit({entry})}><Plus size={15}/>Add quote</button>}</div>
   {!entry.quotes.length&&<p className="spec-empty-detail">Add the supplier’s total and attach their quote. Each alternative stays inside this entry.</p>}
   {entry.quotes.map(quote=>{const chosen=entry.selectedQuoteId===quote.id,revision=chosen?current!.revision:quote.revisions.at(-1)!,difference=current&&current.quote.currency===quote.currency?revision.amount-current.revision.amount:null;return <div className={'spec-quote '+(chosen?'chosen':'')} key={quote.id}><div className="spec-quote-row"><div className="spec-quote-info"><div><strong>{quote.provider}</strong>{chosen&&<span className="spec-selected"><Check size={13}/>Selected</span>}</div><p>{revision.scope||'Inclusions and exclusions not specified'}</p><small>{revision.date}{revision.leadTime?' · '+revision.leadTime:''}</small><div className="spec-inline-actions">{revision.fileId&&<button className="spec-link" onClick={()=>openFile(revision.fileId)}><FileText size={14}/>Quote attachment</button>}{revision.url&&<a className="spec-link" href={revision.url} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>Quote link</a>}{canEdit&&!entry.archived&&<button className="spec-link" disabled={busy} onClick={()=>setQuoteEdit({entry,quote})}>Add revision</button>}</div></div><div className="spec-quote-price"><strong>{specMoney(revision.amount,quote.currency)}</strong><small>{quote.currency}{!chosen&&difference!==null?' · '+(difference<0?'−':'+')+specMoney(Math.abs(difference),quote.currency):''}</small></div>{canEdit&&!entry.archived&&<button className="button outline" disabled={busy||chosen} onClick={()=>update(entry,{selectedQuoteId:quote.id,selectedRevisionId:revision.id,stage:'Selected'})}>{chosen?'Selected':'Select'}</button>}</div>
    {quote.revisions.length>1&&<details className="spec-revisions"><summary>{quote.revisions.length} revisions</summary>{[...quote.revisions].reverse().map((rev,i)=><div key={rev.id}><div><strong>Revision {quote.revisions.length-i}</strong><small>{rev.date} · {specMoney(rev.amount,quote.currency)}</small><p>{rev.scope}</p></div><div className="spec-inline-actions">{rev.fileId&&<button className="spec-link" onClick={()=>openFile(rev.fileId)}>Open file</button>}{rev.url&&<a className="spec-link" href={rev.url} target="_blank" rel="noopener noreferrer">Open link</a>}{canEdit&&!entry.archived&&<button className="button outline" disabled={busy||entry.selectedRevisionId===rev.id} onClick={()=>update(entry,{selectedQuoteId:quote.id,selectedRevisionId:rev.id,stage:chosen&&entry.stage!=='Quoting'?entry.stage:'Selected'})}>{entry.selectedRevisionId===rev.id?'Selected':'Use revision'}</button>}</div></div>)}</details>}
   </div>})}
   {entry.quotes.length>1&&<p className="spec-footnote">Compare scope, tax, delivery and installation before selecting. Price differences use the quoted totals; currencies are kept separate.</p>}
  </div>
 }
 function paymentPanel(entry:Specification){const offer=selectedOffer(entry),paid=quotePaid(entry),direct=directlyPurchased(entry);return <div><div className="spec-panel-heading"><span>Payment history</span>{canEdit&&direct&&!entry.archived&&<button className="button outline" disabled={busy||!entry.quotes.length} onClick={()=>setPaymentEdit(entry)}><Plus size={15}/>Record payment</button>}</div>{!direct&&<p className="spec-empty-detail">{entry.purchasedBy==='Contractor'?'Included in the contractor’s scope.':'For reference only.'} The price stays in the schedule and is excluded from direct purchases and balances.</p>}{offer&&direct&&<div className="spec-payment-totals"><span><small>{offer.quote.provider} · paid</small><strong>{specMoney(paid,offer.quote.currency)}</strong></span><span><small>{paid>offer.revision.amount?'Overpaid':'Balance on selection'}</small><strong>{specMoney(Math.abs(offer.revision.amount-paid),offer.quote.currency)}</strong></span></div>}{entry.payments.some(p=>!p.voided&&p.quoteId!==entry.selectedQuoteId)&&<p className="spec-payment-note">Payments to other suppliers remain in the history and paid total. They do not reduce the selected supplier’s balance.</p>}{!entry.payments.length&&direct&&<p className="spec-empty-detail">No payments recorded.</p>}<div className="spec-payments">{[...entry.payments].sort((a,b)=>b.date.localeCompare(a.date)).map(payment=>{const quote=entry.quotes.find(q=>q.id===payment.quoteId)!;return <div className={'spec-payment '+(payment.voided?'voided':'')} key={payment.id}><div><strong>{payment.note||'Payment'}{payment.voided?' · Voided':''}</strong><small>{payment.date} · {payment.payer} · {quote.provider}</small></div><strong>{specMoney(payment.amount,quote.currency)}</strong><div className="spec-inline-actions">{payment.receiptId&&<button className="spec-link" onClick={()=>openFile(payment.receiptId)}>Receipt</button>}{canEdit&&!entry.archived&&<button className="spec-link" disabled={busy} onClick={()=>update(entry,{payments:entry.payments.map(p=>p.id===payment.id?{...p,voided:!p.voided}:p)})}>{payment.voided?'Restore':'Void'}</button>}</div></div>})}</div></div>}
 function detailPanel(entry:Specification){return <div><div className="spec-panel-heading"><span>{entry.purchasedBy==='Contractor'?'Contractor scope':entry.purchasedBy==='Reference only'?'Reference only':entry.purchasedBy+' purchase'}</span>{canEdit&&<button className="button outline" disabled={busy} onClick={()=>setEdit(entry)}><Pencil size={15}/>Edit entry</button>}</div>{entry.description&&<p className="spec-description">{entry.description}</p>}<div className="spec-detail-images">{[entry.photoId,entry.referenceId].map((id,index)=>{const file=assets.find(f=>f.id===id);return file?<button key={index} aria-label={'Open '+(index?'reference image':'product photo')} onClick={()=>openFile(file.id)}><AssetPreview file={file} projectId={projectId} headers={headers}/><span>{index?'Render / reference':'Product photo'}</span></button>:null})}</div>{entry.notes&&<div className="spec-note"><small>Notes</small><p>{entry.notes}</p></div>}{canEdit&&<button className="spec-link spec-archive" disabled={busy} onClick={()=>{if(entry.archived)update(entry,{archived:false});else{setConfirm({entry});setConfirmError('')}}}><Archive size={15}/>{entry.archived?'Restore entry':'Archive entry'}</button>}</div>}
 function entryRow(entry:Specification){const source=entry.priceSourceId?entries.find(e=>e.id===entry.priceSourceId):null,priced=source||entry,offer=selectedOffer(priced),photo=assets.find(f=>f.id===entry.photoId),paid=quotePaid(priced),direct=directlyPurchased(priced),open=openId===entry.id;return <article className="spec-entry" key={entry.id}><div className="spec-entry-row"><button className="spec-thumbnail" aria-label={'Edit details of '+entry.name} onClick={()=>toggle(entry.id,'details')}>{photo?<AssetPreview file={photo} projectId={projectId} headers={headers}/>:<ImagePlus size={23}/>}</button><div className="spec-entry-name"><button onClick={()=>toggle(entry.id,'details')}>{entry.name}</button><p>{offer?.quote.provider||entry.description||'No supplier selected'}</p>{source?<button className="spec-link" onClick={()=>{onGroup('all');setOpenId(source.id);setPanel('quotes')}}><Link2 size={13}/>Included in {source.name}</button>:<button className="spec-link" aria-expanded={open&&panel==='quotes'} onClick={()=>toggle(entry.id,'quotes')}>{entry.quotes.length} {entry.quotes.length===1?'quote':'quotes'}{entry.quotes.length>1?' · Compare':''}<ChevronDown size={13}/></button>}</div><div className="spec-row-price"><strong>{offer?specMoney(offer.revision.amount,offer.quote.currency):'—'}</strong><small>{source?'Package total':!offer?'Not selected':direct?offer.quote.currency+' · Selected':offer.quote.currency+' · Reference'}</small></div><div className="spec-row-status"><Choice label={'Progress of '+entry.name} value={entry.stage} disabled={!canEdit||busy||entry.archived||(!offer&&!source)} onChange={v=>update(entry,{stage:v as Specification['stage']})} options={specificationStages.map(s=>({value:s,label:s}))}/><button className="spec-link" onClick={()=>toggle(entry.id,source?'details':'payments')}>{source?'Price counted in package':!direct?entry.purchasedBy==='Contractor'?'Contractor scope':'Reference only':offer?(paid>=offer.revision.amount&&offer.revision.amount>0?'Paid in full':specMoney(paid,offer.quote.currency)+' paid'):'No payments'}</button></div></div>{open&&<div className="spec-entry-detail"><div className="spec-detail-header"><Tabs value={panel} onValueChange={setPanel}><TabsList variant="line"><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="quotes" disabled={!!source}>Quotes</TabsTrigger><TabsTrigger value="payments" disabled={!!source}>Payments</TabsTrigger></TabsList></Tabs><button className="icon-button" aria-label="Close specification details" onClick={()=>setOpenId(null)}><X size={17}/></button></div>{source||panel==='details'?detailPanel(entry):panel==='payments'?paymentPanel(entry):offerPanel(entry)}</div>}</article>}

 return <main className="overview-page specifications-page"><div className="overview-heading"><div><h1>{activeGroup?.name||(group==='archived'?'Archived specifications':'Specifications')}</h1><p>{projectName}</p></div><div className="overview-heading-actions">{canEdit&&<><button className="button outline" onClick={()=>onCreateGroupOpenChange(true)}><FolderPlus size={16}/>New group</button><button className="button primary" onClick={newEntry}><Plus size={16}/>New entry</button></>}</div></div>
  <div className="specification-toolbar"><label className="searchbox"><Search size={16}/><input placeholder="Search specifications" aria-label="Search specifications" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="spec-mobile-groups"><Choice label="Filter specification group" value={group} onChange={onGroup} options={[{value:'all',label:'All specifications'},{value:'ungrouped',label:'Ungrouped'},...groups.map(g=>({value:g.id,label:g.name})),{value:'archived',label:'Archived'}]}/></div>{activeGroup&&canEdit&&<><button className="icon-button" aria-label="Rename specification group" onClick={()=>{setGroupEdit(activeGroup);setGroupName(activeGroup.name);setGroupError('')}}><Pencil size={16}/></button><button className="icon-button" aria-label="Remove specification group" onClick={()=>{setConfirm({group:activeGroup});setConfirmError('')}}><Trash2 size={16}/></button></>}<span className="spec-count">{matching.length} {matching.length===1?'entry':'entries'}</span></div>
  {totals.length>0&&<div className="spec-summary" aria-label="Active project specification totals">{totals.map(t=><div key={t.currency}><strong>{t.currency}</strong><span>Selected purchases <b>{specMoney(t.selected,t.currency)}</b></span><span>Paid <b>{specMoney(t.paid,t.currency)}</b></span><span>Remaining <b>{specMoney(t.balance,t.currency)}</b></span>{t.reference>0&&<span className="spec-reference-total">Reference <b>{specMoney(t.reference,t.currency)}</b></span>}</div>)}<small>Project totals · Active entries · Reference prices excluded from purchases</small></div>}
  {error&&<div className="error-banner" role="alert">{error}<button className="spec-link" onClick={()=>void load().catch(e=>setError(e.message))}>Retry</button></div>}
  {loading?<div className="overview-loading"><LoaderCircle className="spin"/>Loading specifications…</div>:sections.map(section=>{const list=matching.filter(e=>(e.groupId||'ungrouped')===section.id);if(!list.length&&(group==='all'||group==='archived'||query))return null;return <section className="spec-group" key={section.id}><h2><Folder size={16}/>{section.name}<span>{list.length}</span></h2>{list.map(entryRow)}{!list.length&&<p className="spec-empty-detail">No entries in this group yet.</p>}</section>})}
  {!loading&&!matching.length&&(!activeGroup||query)&&<div className="overview-empty"><BookOpen size={32}/><h2>{query?'No matching specifications':group==='archived'?'No archived entries':'Your specification schedule'}</h2><p>{query?'Try a product, package or supplier name.':'Create groups and add products or whole supplier packages.'}</p>{canEdit&&!query&&group!=='archived'&&<button className="button primary" onClick={newEntry}><Plus size={16}/>Add first entry</button>}</div>}
  {!loading&&<section className="spec-document-section"><div><button className="spec-link" aria-expanded={documentsOpen} onClick={()=>setDocumentsOpen(v=>!v)}><FileText size={16}/>Specification documents · {documents.length}<ChevronDown size={14}/></button>{canEdit&&<button className="button outline" disabled={busy} onClick={()=>input.current?.click()}><Upload size={15}/>Upload PDFs</button>}</div><input ref={input} hidden multiple type="file" accept="application/pdf,.pdf" aria-label="Upload specification documents" onChange={e=>{const items=newUploadItems(Array.from(e.target.files||[]));setUploadQueue(items);void uploadDocuments(items)}}/><UploadQueue items={uploadQueue} busy={busy||uploading} onRetry={()=>void uploadDocuments(uploadQueue)} onClear={()=>setUploadQueue([])}/>{documentsOpen&&<div className="document-list">{documents.map(file=><div className="document-row" key={file.id}><FileText size={18}/><button className="document-name" onClick={()=>openFile(file.id)}><strong>{file.name}</strong><small>{new Date(file.created).toLocaleDateString()}</small></button><button className="icon-button" aria-label={'Download '+file.name} onClick={()=>void download(file)}><Download size={17}/></button></div>)}{!documents.length&&<p className="spec-empty-detail">Upload existing specification PDFs here.</p>}</div>}</section>}
  {edit&&<SpecificationEntryForm key={edit.id} {...common} entry={edit} entries={entries} groups={groups} onClose={()=>setEdit(null)} onSave={async entry=>{await saveEntry(entry);onGroup(entry.groupId||'ungrouped');setOpenId(entry.id);setPanel(entry.quotes.length?'details':'quotes')}}/>}
  {quoteEdit&&<SpecificationQuoteForm key={quoteEdit.quote?.id||'new-quote'} {...common} {...quoteEdit} onClose={()=>setQuoteEdit(null)} onSave={saveEntry}/>}
  {paymentEdit&&<SpecificationPaymentForm key={paymentEdit.id} {...common} entry={paymentEdit} onClose={()=>setPaymentEdit(null)} onSave={saveEntry}/>}
  <Dialog open={createGroupOpen||!!groupEdit} onOpenChange={v=>{if(!v&&!busy){onCreateGroupOpenChange(false);setGroupEdit(null)}}}><DialogContent className="asset-name-dialog"><DialogHeader><DialogTitle>{groupEdit?'Rename specification group':'New specification group'}</DialogTitle><DialogDescription>For example Lighting, Furniture or Finishes.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);writes.current++;sequence.current++;setGroupError('');try{const r=await request('/api/specifications',{method:'POST',body:JSON.stringify({action:'group',projectId,id:groupEdit?.id,version:groupEdit?.version,name:groupName})});setGroups(r.groups);onGroup(r.id);setGroupEdit(null);onCreateGroupOpenChange(false)}catch(e:any){setGroupError(e.message)}finally{writes.current--;sequence.current++;setBusy(false)}}}><label>Group name<input autoFocus required maxLength={100} value={groupName} onChange={e=>setGroupName(e.target.value)}/></label>{groupError&&<p className="form-error" role="alert">{groupError}</p>}<button className="button primary" disabled={busy}>Save group</button></form></DialogContent></Dialog>
  <Dialog open={!!confirm} onOpenChange={v=>!v&&!busy&&setConfirm(null)}><DialogContent><DialogHeader><DialogTitle>{confirm?.group?'Remove this group?':'Archive this specification?'}</DialogTitle><DialogDescription>{confirm?.group?'Entries stay in the project and become ungrouped.':'The entry and its quote and payment history are kept in Archived. Archived entries are excluded from active project totals.'}</DialogDescription></DialogHeader>{confirmError&&<p className="form-error" role="alert">{confirmError}</p>}<button className="button primary" disabled={busy} onClick={async()=>{if(!confirm)return;setConfirmError('');try{if(confirm.entry)await saveEntry({...confirm.entry,archived:true});else if(confirm.group){setBusy(true);writes.current++;sequence.current++;try{const r=await request('/api/specifications',{method:'POST',body:JSON.stringify({projectId,action:'removeGroup',id:confirm.group.id,version:confirm.group.version})});setGroups(r.groups);setEntries(r.entries);onGroup('all')}finally{setBusy(false);writes.current--;sequence.current++;}}setConfirm(null);setOpenId(null)}catch(e:any){setConfirmError(e.message)}}}>{busy?'Saving…':confirm?.group?'Remove group':'Archive entry'}</button></DialogContent></Dialog>
  <Dialog open={!!preview} onOpenChange={async v=>{if(!v&&(preview?.mime!=='application/pdf'||await flushOpenDrawings()))setPreview(null)}}><DialogContent className="project-asset-dialog"><DialogHeader><DialogTitle>{preview?.name}</DialogTitle><DialogDescription>Specification attachment</DialogDescription></DialogHeader>{preview&&<><AssetPreview file={preview} projectId={projectId} headers={headers} large/><div className="asset-detail-actions"><button className="button outline" onClick={()=>void download(preview)}><Download size={16}/>Download original</button></div></>}</DialogContent></Dialog>
 </main>
}
