"use client";
import {useRef,useState} from 'react';
import {ImagePlus,Images,LoaderCircle,Upload,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Choice} from './review-controls';
import AssetPreview from './asset-preview';
import PhotoLibraryPicker from './photo-library-picker';
import {uid,type ProjectAsset} from '@/lib/review-types';
import {uploadFile,uploadThumbnail,type Requester} from '@/lib/upload-client';
import {parseSpecAmount,purchaseModes,specificationCurrencies,type Specification,type SpecGroup,type SupplierQuote} from '@/lib/specifications';

type Common={projectId:string;request:Requester;headers:Record<string,string>;assets:ProjectAsset[];onAsset:(asset:ProjectAsset)=>void};
const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};

export function SpecificationFileField({label,value,onChange,disabled,onUploading,...common}:Common&{label:string;value:string|null;onChange:(id:string|null)=>void;disabled?:boolean;onUploading?:(v:boolean)=>void}){
 const input=useRef<HTMLInputElement>(null),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 return <div className="spec-file-field"><label>{label}</label><div><Choice label={label} disabled={disabled||uploading} value={value||'none'} onChange={v=>onChange(v==='none'?null:v)} options={[{value:'none',label:'No attachment'},...common.assets.filter(f=>f.source==='project'&&f.kind!=='photo').map(f=>({value:f.id,label:f.name})),...(value&&!common.assets.some(f=>f.id===value)?[{value,label:'Attached file'}]:[])]}/><button type="button" className="button outline" disabled={disabled||uploading} onClick={()=>input.current?.click()}>{uploading?<LoaderCircle size={16} className="spin"/>:<Upload size={16}/>}Upload</button></div><input ref={input} type="file" hidden aria-label={'Upload '+label.toLowerCase()} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);onUploading?.(true);setError('');try{const result=await uploadFile(common.request,common.projectId,file,'document',{kind:'file'});common.onAsset(result.asset);onChange(result.asset.id)}catch(e:any){setError(e.message)}finally{setUploading(false);onUploading?.(false);if(input.current)input.current.value=''}}}/>{error&&<p className="form-error" role="alert">{error}</p>}</div>
}

export function SpecificationEntryForm({entry,entries,groups,onClose,onSave,...common}:Common&{entry:Specification;entries:Specification[];groups:SpecGroup[];onClose:()=>void;onSave:(entry:Specification)=>Promise<void>}){
 const [draft,setDraft]=useState(entry),[busy,setBusy]=useState(false),[error,setError]=useState(''),[photoSlot,setPhotoSlot]=useState<'photoId'|'referenceId'|null>(null),[uploading,setUploading]=useState(false),[uploadSlot,setUploadSlot]=useState<'photoId'|'referenceId'>('photoId'),input=useRef<HTMLInputElement>(null);
 function patch<K extends keyof Specification>(key:K,value:Specification[K]){setDraft(old=>({...old,[key]:value}))}
 return <><Dialog open onOpenChange={v=>!v&&!busy&&!uploading&&onClose()}><DialogContent className="spec-edit-dialog"><DialogHeader><DialogTitle>{entry.version?'Edit specification':'New specification'}</DialogTitle><DialogDescription>A single product or a complete supplier package.</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(draft);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
  <label>Name<input autoFocus required maxLength={200} value={draft.name} onChange={e=>patch('name',e.target.value)} placeholder="e.g. Lighting supply package"/></label>
  <div className="form-grid"><label>Group<Choice label="Specification group" value={draft.groupId||'ungrouped'} onChange={v=>patch('groupId',v==='ungrouped'?null:v)} options={[{value:'ungrouped',label:'Ungrouped'},...groups.map(g=>({value:g.id,label:g.name}))]}/></label><label>Purchased by<Choice label="Purchased by" value={draft.purchasedBy} onChange={v=>patch('purchasedBy',v as Specification['purchasedBy'])} options={purchaseModes.map(v=>({value:v,label:v==='Contractor'?'Contractor scope':v}))}/></label></div>
  <label>Description / scope<textarea rows={3} value={draft.description} maxLength={5000} onChange={e=>patch('description',e.target.value)} placeholder="What is included in this entry?"/></label>
  {!draft.quotes.length&&!draft.payments.length&&<label>Quote package<Choice label="Quote package" value={draft.priceSourceId||'own'} onChange={v=>setDraft(old=>({...old,priceSourceId:v==='own'?null:v,stage:v==='own'?'Quoting':old.stage}))} options={[{value:'own',label:'Own supplier quotes'},...entries.filter(e=>e.id!==entry.id&&!e.archived&&!e.priceSourceId&&e.quotes.length).map(e=>({value:e.id,label:'Included in '+e.name}))]}/></label>}
  <div className="spec-photo-fields">{(['photoId','referenceId'] as const).map(slot=>{const file=common.assets.find(f=>f.id===draft[slot]);return <div key={slot}><span className="field-label">{slot==='photoId'?'Product photo':'Render / reference'}</span><div className="spec-edit-photo">{file?<AssetPreview file={file} projectId={common.projectId} headers={common.headers}/>:<ImagePlus size={28}/>}</div><div className="spec-photo-actions"><button type="button" className="button outline" disabled={busy||uploading} onClick={()=>setPhotoSlot(slot)}><Images size={15}/>Library</button><button type="button" className="icon-button" aria-label={'Upload '+(slot==='photoId'?'product photo':'reference image')} disabled={busy||uploading} onClick={()=>{setUploadSlot(slot);input.current?.click()}}><Upload size={17}/></button>{file&&<button type="button" className="icon-button" aria-label={'Remove '+(slot==='photoId'?'product photo':'reference image')} onClick={()=>patch(slot,null)}><X size={16}/></button>}</div></div>})}</div>
  <input ref={input} hidden type="file" accept="image/*" aria-label="Upload specification image" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setError('');try{const result=await uploadFile(common.request,common.projectId,file,'document',{kind:'photo'});if(!result.asset.mime.startsWith('image/'))throw Error('Choose a supported image file.');common.onAsset(result.asset);patch(uploadSlot,result.asset.id);await uploadThumbnail(common.request,common.projectId,result.asset.id,file).catch(()=>false)}catch(e:any){setError(e.message)}finally{setUploading(false);if(input.current)input.current.value=''}}}/>
  <label>Notes<textarea rows={2} maxLength={5000} value={draft.notes} onChange={e=>patch('notes',e.target.value)}/></label>
  {draft.priceSourceId&&<p className="form-note">The selected package holds the quotes and payments. Its price is counted once.</p>}{['Contractor','Reference only'].includes(draft.purchasedBy)&&<p className="form-note">Kept in the specification schedule, outside direct-purchase totals and balances.</p>}
  {error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy||uploading}>{busy||uploading?<LoaderCircle className="spin" size={16}/>:null}{uploading?'Uploading image…':busy?'Saving…':'Save entry'}</button>
 </form></DialogContent></Dialog><PhotoLibraryPicker open={!!photoSlot} onOpenChange={v=>!v&&setPhotoSlot(null)} purpose="specification" projectId={common.projectId} headers={common.headers} request={common.request} onChoose={file=>{common.onAsset(file);if(photoSlot)patch(photoSlot,file.id);setPhotoSlot(null)}}/></>
}

export function SpecificationQuoteForm({entry,quote,onClose,onSave,...common}:Common&{entry:Specification;quote?:SupplierQuote;onClose:()=>void;onSave:(entry:Specification)=>Promise<void>}){
 const previous=quote?.revisions.at(-1),[provider,setProvider]=useState(quote?.provider||''),[currency,setCurrency]=useState(quote?.currency||entry.quotes[0]?.currency||'USD'),[price,setPrice]=useState(previous?String(previous.amount/100):''),[date,setDate]=useState(localDate()),[leadTime,setLeadTime]=useState(previous?.leadTime||''),[scope,setScope]=useState(previous?.scope||''),[url,setUrl]=useState(''),[fileId,setFileId]=useState<string|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 return <Dialog open onOpenChange={v=>!v&&!busy&&!uploading&&onClose()}><DialogContent className="spec-edit-dialog"><DialogHeader><DialogTitle>{quote?'New quote revision':'Add supplier quote'}</DialogTitle><DialogDescription>{entry.name}{quote?' · Previous revisions stay in the history.':' · Quote the complete scope or package.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const revision={id:uid(),amount:parseSpecAmount(price),date,leadTime,scope,fileId,url,created:new Date().toISOString()},supplier:SupplierQuote=quote?{...quote,revisions:[...quote.revisions,revision]}:{id:uid(),provider,currency:currency as SupplierQuote['currency'],revisions:[revision]};await onSave({...entry,quotes:quote?entry.quotes.map(q=>q.id===quote.id?supplier:q):[...entry.quotes,supplier]});onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
  <label>Supplier / provider<input required disabled={!!quote} value={provider} maxLength={180} onChange={e=>setProvider(e.target.value)}/></label><div className="form-grid"><label>Total quote price<input required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.00"/></label><label>Currency<Choice label="Quote currency" value={currency} disabled={!!quote} onChange={v=>setCurrency(v as SupplierQuote['currency'])} options={specificationCurrencies.map(c=>({value:c,label:c}))}/></label></div><div className="form-grid"><label>Quote date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Delivery / lead time<input value={leadTime} maxLength={200} onChange={e=>setLeadTime(e.target.value)} placeholder="e.g. 6–8 weeks"/></label></div><label>Included / excluded<textarea rows={3} value={scope} maxLength={3000} onChange={e=>setScope(e.target.value)} placeholder="Tax included. Delivery and installation excluded."/></label><SpecificationFileField {...common} label="Quote attachment" value={fileId} onChange={setFileId} disabled={busy} onUploading={setUploading}/><label>Quote link · optional<input type="url" value={url} maxLength={2000} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy||uploading}>{busy?<LoaderCircle className="spin" size={16}/>:null}{quote?'Save revision':'Add quote'}</button>
 </form></DialogContent></Dialog>
}

export function SpecificationPaymentForm({entry,onClose,onSave,...common}:Common&{entry:Specification;onClose:()=>void;onSave:(entry:Specification)=>Promise<void>}){
 const [quoteId,setQuoteId]=useState(entry.selectedQuoteId||entry.quotes[0]?.id||''),[price,setPrice]=useState(''),[date,setDate]=useState(localDate()),[payer,setPayer]=useState(entry.purchasedBy==='Owner'?'Owner':'Studio'),[note,setNote]=useState(''),[receiptId,setReceiptId]=useState<string|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');const quote=entry.quotes.find(q=>q.id===quoteId);
 return <Dialog open onOpenChange={v=>!v&&!busy&&!uploading&&onClose()}><DialogContent className="spec-edit-dialog"><DialogHeader><DialogTitle>Record payment</DialogTitle><DialogDescription>{entry.name}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const amount=parseSpecAmount(price);if(amount<=0)throw Error('Enter an amount greater than zero.');await onSave({...entry,payments:[...entry.payments,{id:uid(),quoteId,amount,date,payer,note,receiptId,voided:false}]});onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
  <label>Supplier quote<Choice label="Payment supplier" value={quoteId} onChange={setQuoteId} options={entry.quotes.map(q=>({value:q.id,label:q.provider+' · '+q.currency}))}/></label><div className="form-grid"><label>Amount · {quote?.currency}<input required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.00"/></label><label>Payment date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Paid by<input value={payer} required maxLength={160} onChange={e=>setPayer(e.target.value)}/></label><label>Note<input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="e.g. 30% deposit"/></label><SpecificationFileField {...common} label="Payment receipt" value={receiptId} onChange={setReceiptId} onUploading={setUploading} disabled={busy}/>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy||uploading||!quote}>{busy?<LoaderCircle className="spin" size={16}/>:null}Record payment</button>
 </form></DialogContent></Dialog>
}
