"use client";
import {flushOpenDrawings} from '@/lib/document-drawings';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Camera,Check,Users,Download,FileText,Image as ImageIcon,LoaderCircle,MapPin,Paperclip,Send,Trash2,X,ZoomIn,ZoomOut} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Attachment,TaskPhoto,Comment,Member,RecordItem,Sheet,Task,professionNames,statusNames,uid} from '@/lib/review-types';
import PlanPreview from './plan-preview';
import {Choice,professionOptions} from './review-controls';
import {uploadFile,uploadThumbnail,DOCUMENT_LIMIT} from '@/lib/upload-client';
import AssetPreview from './asset-preview';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
const fileSize=(n:number)=>n<1024*1024?Math.max(1,Math.round(n/1024))+' KB':(n/1024/1024).toFixed(1)+' MB';
type Media=Attachment&{source?:'project'|'task'};
function AttachmentImage({file,projectId,headers,large=false}:{file:Media;projectId:string;headers:Record<string,string>;large?:boolean}){
 return <AssetPreview file={{...file,source:file.source||'task'}} projectId={projectId} headers={headers} large={large}/>;
}
export default function TaskDialog({open,onOpenChange,task,remoteTask,onTaskChange,sheets,comments,projectId,headers,request,role,userId,name,onSave,onComment,onDelete,onLocate,onOpenPlan}:{open:boolean;onOpenChange:(v:boolean)=>void;task:Task|null;remoteTask?:Task;onTaskChange:(t:Task)=>void;sheets:Sheet[];comments:Comment[];projectId:string;headers:Record<string,string>;request:Requester;role:string;userId?:string;name:string;onSave:(t:Task)=>Promise<Task>;onComment:(c:Comment)=>Promise<RecordItem>;onDelete:(t:Task)=>void;onLocate:(t:Task)=>void;onOpenPlan:(id:string)=>void}){
 const [busy,setBusy]=useState(false),[text,setText]=useState(''),[files,setFiles]=useState<File[]>([]),[panel,setPanel]=useState('details'),[job,setJob]=useState('all'),[sort,setSort]=useState('time'),[focus,setFocus]=useState(false),[activeFile,setActiveFile]=useState<Media|null>(null),[members,setMembers]=useState<Member[]>([]),[progress,setProgress]=useState('');
 const baseTask=useRef<Task|null>(null),photoInput=useRef<HTMLInputElement>(null),photoCamera=useRef<HTMLInputElement>(null);
 const uploadInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null),modalBody=useRef<HTMLDivElement>(null),chatScroll=useRef<HTMLDivElement>(null),uploaded=useRef(new Map<File,Attachment>()),api=useRef(request);api.current=request;
 useEffect(()=>{if(open){baseTask.current=task;setText('');setFiles([]);uploaded.current.clear();setPanel('details');setJob('all');setFocus(false);setActiveFile(null);if(role!=='client')api.current('/api/members?project='+projectId).then(r=>setMembers(r.members)).catch(()=>{})}},[open,task?.id,projectId]);
 useEffect(()=>{if(!open)return;requestAnimationFrame(()=>{if(modalBody.current)modalBody.current.scrollTop=0;if(chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight})},[open,task?.id]);
 useEffect(()=>{if(panel==='chat'&&chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight},[comments.length,panel]);
 useEffect(()=>{if(!open||!task?.version||!remoteTask||remoteTask.version===task.version||busy)return;if(JSON.stringify(task)===JSON.stringify(baseTask.current)){baseTask.current=remoteTask;onTaskChange(remoteTask)}},[open,remoteTask,task,busy]);
 const changedElsewhere=!!task?.version&&!!remoteTask&&remoteTask.version!==task.version;
 const deletedElsewhere=!!task?.version&&!remoteTask;
 const sheet=sheets.find(s=>s.id===task?.sheetId),client=role==='client',readOnly=client&&!!task?.version;
 const media=Array.from(new Map([...(task?.photos||[]),...comments.flatMap(c=>c.attachments||[])].map(a=>[a.id,a])).values()),shown=comments.filter(c=>job==='all'||(c.authorRole||'internal')===job).slice().sort((a,b)=>sort==='role'?(a.authorRole||'internal').localeCompare(b.authorRole||'internal')||a.created.localeCompare(b.created):a.created.localeCompare(b.created));
 function addFiles(incoming:File[]){const available=8-files.length;if(incoming.some(f=>f.size>DOCUMENT_LIMIT)){toast.error('Each attachment can be up to 200 MB.');return}if(incoming.length>available)toast('You can attach up to 8 files per message.');setFiles(old=>[...old,...incoming.slice(0,available)])}
 async function save(e:React.FormEvent){e.preventDefault();if(!task)return;setBusy(true);try{const saved=await onSave({...task,title:task.title.trim()});baseTask.current=saved;onTaskChange(saved);toast.success(task.version?'Task updated':'Task created')}catch{}finally{setBusy(false)}}
 async function send(e?:React.FormEvent){e?.preventDefault();if(!task?.version||busy||(!text.trim()&&!files.length))return;setBusy(true);try{
  const attachments:Attachment[]=[];
  for(let i=0;i<files.length;i++){const file=files[i];setProgress('Uploading '+(i+1)+' of '+files.length);let attachment=uploaded.current.get(file);if(!attachment){attachment=(await uploadFile(request,projectId,file,'attachment',{taskId:task.id},n=>setProgress('File '+(i+1)+' · '+n+'%'))).attachment as Attachment;uploaded.current.set(file,attachment);await uploadThumbnail(request,projectId,attachment.id,file).catch(()=>false)}attachments.push(attachment)}
  setProgress('Sending');await onComment({id:uid(),type:'comment',sheetId:task.sheetId,taskId:task.id,text:text.trim(),attachments,author:name,created:new Date().toISOString(),visibility:task.visibility,audience:[]});setText('');setFiles([]);uploaded.current.clear();setPanel('chat');
 }catch(e:any){toast.error(e.message)}finally{setProgress('');setBusy(false)}}
 async function uploadTaskPhotos(incoming:File[]){if(!task||busy)return;setBusy(true);let next=task;try{const room=8-(task.photos?.length||0);if(incoming.length>room)toast('Up to 8 cover photos per task.');for(const file of incoming.slice(0,room)){setProgress('Uploading '+file.name);const r=await uploadFile(request,projectId,file,'document',{kind:'photo'},n=>setProgress('Photo · '+n+'%'));await uploadThumbnail(request,projectId,r.asset.id,file).catch(()=>false);next={...next,photos:[...(next.photos||[]),r.asset]};onTaskChange(next)}toast('Photos added. Save the task to keep the links.')}catch(e:any){toast.error(e.message)}finally{setBusy(false);setProgress('')}}
 async function download(file:Media){try{const r=await fetch('/api/'+(file.source==='project'?'documents':'attachments')+'?project='+projectId+'&id='+file.id+'&download=1',{headers});if(!r.ok)throw new Error('This attachment could not be downloaded.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){toast.error(e.message)}}
 function attachment(file:Media){return <button key={file.id} className={'attachment-card '+(file.mime.startsWith('image/')?'photo':'file')} onClick={()=>(file.mime.startsWith('image/')||file.mime==='application/pdf')?setActiveFile(file):download(file)} type="button">{file.mime.startsWith('image/')?<AttachmentImage file={file} projectId={projectId} headers={headers}/>:<FileText size={27}/>}<span><strong>{file.name}</strong><small>{fileSize(file.size)}</small></span></button>}
 return <><Dialog open={open} onOpenChange={v=>!busy&&onOpenChange(v)}><DialogContent className="task-dialog" onInteractOutside={e=>{if(text.trim()||files.length||busy)e.preventDefault()}}><DialogHeader className="task-modal-header"><DialogDescription>{task?.version?'TASK #'+String(task.number).padStart(2,'0'):'NEW TASK'}{sheet?' · '+sheet.code:''}</DialogDescription><DialogTitle>{task?.version?task.title:'What needs to change?'}</DialogTitle></DialogHeader>
 {task&&<div className="mobile-task-tabs"><button className={panel==='details'?'active':''} onClick={()=>setPanel('details')}><FileText size={15}/> Details</button><button className={panel==='chat'?'active':''} onClick={()=>setPanel('chat')}>Conversation <span>{comments.length}</span></button><button className={panel==='media'?'active':''} onClick={()=>setPanel('media')}><Paperclip size={15}/> Files <span>{media.length}</span></button></div>}
 {(changedElsewhere||deletedElsewhere)&&<div className="task-sync-notice" role="status">{deletedElsewhere?'This task was removed on another device. Your draft is still here.':'This task changed on another device. Your draft has been kept.'}{remoteTask&&<button type="button" onClick={()=>{if(window.confirm('Replace your unsaved task edits with the latest saved version?')){baseTask.current=remoteTask;onTaskChange(remoteTask)}}}>Load latest version</button>}</div>}
 {task&&<div className={'task-modal-columns panel-'+panel} ref={modalBody}><section className="task-information"><div className="task-photo-first">{task.photos?.length?<><button className="task-main-photo" aria-label="Open task cover photo" onClick={()=>setActiveFile(task.photos![0])}><AssetPreview file={task.photos[0]} projectId={projectId} headers={headers}/></button>{task.photos.length>1&&<div className="task-photo-strip">{task.photos.slice(1).map(p=><button key={p.id} onClick={()=>setActiveFile(p)}><AssetPreview file={p} projectId={projectId} headers={headers}/></button>)}</div>}</>:null}{!readOnly&&(task.photos?.length||0)<8&&<div className="task-photo-capture"><button className="button outline" disabled={busy} onClick={()=>photoCamera.current?.click()}><Camera size={17}/> Take photo</button><button className="button outline" disabled={busy} onClick={()=>photoInput.current?.click()}><ImageIcon size={17}/> Add photos</button></div>}{progress&&<span className="upload-progress" role="status">{progress}</span>}<input hidden type="file" accept="image/*" multiple ref={photoInput} onChange={e=>{void uploadTaskPhotos(Array.from(e.target.files||[]));e.target.value=''}}/><input hidden type="file" accept="image/*" capture="environment" ref={photoCamera} onChange={e=>{void uploadTaskPhotos(Array.from(e.target.files||[]));e.target.value=''}}/></div>{sheet&&<div className="task-plan-context">{sheet&&<PlanPreview sheet={sheet} projectId={projectId} headers={headers} pin={task.position} number={task.number} focus={focus}/>}<div className="task-plan-caption"><span><MapPin size={14}/>{sheet?.code} · {task.position?'Pinned location':'No pin yet'}</span>{task.position&&<button type="button" className="icon-button" aria-label={focus?'Show full plan':'Zoom to task pin'} onClick={()=>setFocus(v=>!v)}>{focus?<ZoomOut size={16}/>:<ZoomIn size={16}/>}</button>}<button type="button" onClick={()=>task.sheetId&&onOpenPlan(task.sheetId)}>Open plan <ArrowUpRight size={14}/></button></div></div>}
 <form className="form-stack task-fields" onSubmit={save}><label>Task title<input autoFocus={!task.version} aria-label="Task title" required maxLength={200} value={task.title} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,title:e.target.value})} placeholder="Describe one thing to change"/></label><label>Notes<textarea aria-label="Task notes" rows={3} value={task.description} maxLength={10000} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,description:e.target.value})} placeholder="Add context, dimensions or a question"/></label>
 <label>Room or location<input aria-label="Task location" value={task.location||''} maxLength={200} placeholder="e.g. Living room / terrace" disabled={readOnly||busy} onChange={e=>onTaskChange({...task,location:e.target.value})}/></label><label>Plan (optional)<Choice label="Task plan" value={task.sheetId||'none'} disabled={readOnly||busy} onChange={id=>onTaskChange({...task,sheetId:id==='none'?null:id,position:null})} options={[{value:'none',label:'Project task · no plan'},...sheets.map(s=>({value:s.id,label:s.code+' · '+s.name}))]}/></label>
 <div className="form-grid"><label>Status<Choice label="Task status" value={task.status} disabled={client||busy} onChange={v=>onTaskChange({...task,status:v as Task['status']})} options={Object.entries(statusNames).map(([value,label])=>({value,label}))}/></label><label>Priority<Choice label="Task priority" value={task.priority} disabled={readOnly||busy} onChange={v=>onTaskChange({...task,priority:v as Task['priority']})} options={['low','medium','high'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))}/></label><label>Assigned to<input list="task-people" aria-label="Task assignee" value={task.assignee} disabled={client||busy} onChange={e=>onTaskChange({...task,assignee:e.target.value})}/><datalist id="task-people">{members.map(m=><option key={m.id} value={m.name}/>)}</datalist></label><label>Due date<input type="date" aria-label="Task due date" value={task.due} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,due:e.target.value})}/></label></div>
 <div className="task-role-note"><Users size={14}/> Visible to everyone · {professionNames[task.authorRole||'internal']} tag</div>
 {!client&&<label>Review source<Choice label="Task review source" value={task.source} onChange={v=>onTaskChange({...task,source:v as Task['source']})} disabled={busy} options={['Internal review','Client review','Site visit'].map(value=>({value,label:value}))}/></label>}
 {!readOnly&&<div className="task-form-buttons"><button className="button outline" type="button" disabled={busy||!sheets.length} onClick={()=>onLocate(task)}><MapPin size={15}/>{task.position?'Move pin':'Place pin'}</button><button className="button primary" disabled={busy||changedElsewhere||deletedElsewhere||!task.title.trim()}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {task.version?'Save changes':'Create task'}</button></div>}{task.version&&!client&&<button type="button" className="delete-task" disabled={busy} onClick={()=>onDelete(task)}><Trash2 size={14}/> Delete task</button>}
 </form></section>
 <section className="task-conversation" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(task.version&&!busy)addFiles(Array.from(e.dataTransfer.files))}}><div className="conversation-header"><Tabs value={panel==='media'?'media':'chat'} onValueChange={setPanel}><TabsList variant="line"><TabsTrigger value="chat">Conversation <span>{comments.length}</span></TabsTrigger><TabsTrigger value="media"><Paperclip size={15}/> Attachments <span>{media.length}</span></TabsTrigger></TabsList></Tabs></div>
 {panel!=='media'?<><div className="conversation-filters"><Choice label="Filter conversation by role" value={job} onChange={setJob} options={[{value:'all',label:'All roles'},...professionOptions]}/><Choice label="Sort conversation" value={sort} onChange={setSort} options={[{value:'time',label:'By time'},{value:'role',label:'By role'}]}/></div><div className="chat-messages" ref={chatScroll} aria-live="polite">{shown.map(c=><article key={c.id} className={'chat-message '+(c.creatorId===userId?'own':'')}><div className="chat-author"><strong>{c.author}</strong><span>{professionNames[c.authorRole||'internal']}</span></div><div className="chat-bubble">{c.attachments?.length?<div className="message-attachments">{c.attachments.map(attachment)}</div>:null}{c.text&&<p>{c.text}</p>}<time title={new Date(c.created).toLocaleString()}>{new Date(c.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · {new Date(c.created).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</time></div></article>)}{!shown.length&&<div className="conversation-empty"><span><Paperclip size={23}/></span><h3>{task.version?'Start the conversation':'Create the task first'}</h3><p>{task.version?'Add a message, a site photo or a file.':'Then add messages and photos here.'}</p></div>}</div></>:<div className="task-attachment-gallery"><div className="gallery-summary"><ImageIcon size={16}/>{media.filter(f=>f.mime.startsWith('image/')).length} photos · {media.filter(f=>!f.mime.startsWith('image/')).length} files</div><div className="attachment-grid">{media.map(attachment)}</div>{!media.length&&<div className="conversation-empty"><Paperclip size={25}/><p>Photos and files from this conversation appear here.</p></div>}</div>}
 <form className="chat-composer" onSubmit={send}>{files.length>0&&<div className="pending-attachments">{files.map((file,i)=><div key={i}><Paperclip size={13}/><span>{file.name}</span><button type="button" disabled={busy} aria-label={'Remove '+file.name} onClick={()=>setFiles(items=>items.filter((_,index)=>index!==i))}><X size={14}/></button></div>)}</div>}<textarea aria-label="Message" placeholder={task.version?'Write a message…':'Create the task to add messages'} rows={2} value={text} maxLength={10000} disabled={!task.version||busy} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} onPaste={e=>{const pasted=Array.from(e.clipboardData.files);if(pasted.length){e.preventDefault();addFiles(pasted)}}}/><div className="composer-actions"><input ref={uploadInput} type="file" hidden multiple onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value=''}}/><input ref={cameraInput} type="file" hidden accept="image/*" capture="environment" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value=''}}/><button type="button" className="icon-button" aria-label="Attach photos or files" disabled={!task.version||busy} onClick={()=>uploadInput.current?.click()}><Paperclip size={19}/></button><button type="button" className="icon-button" aria-label="Take a site photo" disabled={!task.version||busy} onClick={()=>cameraInput.current?.click()}><Camera size={19}/></button><span className="composer-visibility">Everyone</span><button className="send-message" aria-label="Send message" disabled={!task.version||busy||(!text.trim()&&!files.length)}>{busy?<LoaderCircle className="spin" size={19}/>:<Send size={19}/>}</button></div>{progress&&<span className="upload-progress" role="status">{progress}</span>}</form>
 </section></div>}
 </DialogContent></Dialog><Dialog open={!!activeFile} onOpenChange={async v=>{if(!v&&(activeFile?.mime!=='application/pdf'||await flushOpenDrawings()))setActiveFile(null)}}><DialogContent className="attachment-lightbox"><DialogHeader><DialogTitle>{activeFile?.name}</DialogTitle><DialogDescription>{activeFile?fileSize(activeFile.size):''}</DialogDescription></DialogHeader>{activeFile&&<><AttachmentImage file={activeFile} projectId={projectId} headers={headers} large/><button className="button outline" onClick={()=>download(activeFile)}><Download size={16}/> Download</button></>}</DialogContent></Dialog></>
}
