"use client";
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Camera,Check,Download,FileText,Image as ImageIcon,LoaderCircle,MapPin,Paperclip,Send,Trash2,X,ZoomIn,ZoomOut} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Attachment,Audience,Comment,Member,Profession,RecordItem,Sheet,Task,professionNames,statusNames,uid} from '@/lib/review-types';
import PlanPreview from './plan-preview';
import {AudienceSelect,Choice,professionOptions} from './review-controls';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
const fileSize=(n:number)=>n<1024*1024?Math.max(1,Math.round(n/1024))+' KB':(n/1024/1024).toFixed(1)+' MB';
function AttachmentImage({file,projectId,headers,large=false}:{file:Attachment;projectId:string;headers:Record<string,string>;large?:boolean}){
 const [src,setSrc]=useState(''),[error,setError]=useState(false);
 useEffect(()=>{let live=true,url='';const controller=new AbortController();fetch('/api/attachments?project='+projectId+'&id='+file.id,{headers,signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Image unavailable');return r.blob()}).then(blob=>{if(live){url=URL.createObjectURL(blob);setSrc(url)}}).catch(()=>live&&setError(true));return()=>{live=false;controller.abort();if(url)URL.revokeObjectURL(url)}},[projectId,file.id]);
 return src?<img className={large?'attachment-large':'attachment-photo'} src={src} alt={file.name}/>:<span className="attachment-loading">{error?<ImageIcon size={24}/>:<LoaderCircle className="spin" size={20}/>}<span>{error?'Preview unavailable':'Loading photo'}</span></span>
}
export default function TaskDialog({open,onOpenChange,task,onTaskChange,sheets,comments,projectId,headers,request,role,userId,name,onSave,onComment,onDelete,onLocate,onOpenPlan}:{open:boolean;onOpenChange:(v:boolean)=>void;task:Task|null;onTaskChange:(t:Task)=>void;sheets:Sheet[];comments:Comment[];projectId:string;headers:Record<string,string>;request:Requester;role:string;userId?:string;name:string;onSave:(t:Task)=>Promise<Task>;onComment:(c:Comment)=>Promise<RecordItem>;onDelete:(t:Task)=>void;onLocate:(t:Task)=>void;onOpenPlan:(id:string)=>void}){
 const [busy,setBusy]=useState(false),[text,setText]=useState(''),[files,setFiles]=useState<File[]>([]),[messageAudience,setMessageAudience]=useState<Audience>([]),[panel,setPanel]=useState('details'),[job,setJob]=useState('all'),[sort,setSort]=useState('time'),[focus,setFocus]=useState(false),[activeFile,setActiveFile]=useState<Attachment|null>(null),[members,setMembers]=useState<Member[]>([]),[progress,setProgress]=useState('');
 const uploadInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null),modalBody=useRef<HTMLDivElement>(null),chatScroll=useRef<HTMLDivElement>(null),uploaded=useRef(new Map<File,Attachment>()),api=useRef(request);api.current=request;
 useEffect(()=>{if(open){setText('');setFiles([]);uploaded.current.clear();setPanel('details');setJob('all');setFocus(false);setActiveFile(null);setMessageAudience([]);if(role!=='client')api.current('/api/members?project='+projectId).then(r=>setMembers(r.members)).catch(()=>{})}},[open,task?.id,projectId]);
 useEffect(()=>{if(!open)return;requestAnimationFrame(()=>{if(modalBody.current)modalBody.current.scrollTop=0;if(chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight})},[open,task?.id]);
 useEffect(()=>{if(panel==='chat'&&chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight},[comments.length,panel]);
 const sheet=sheets.find(s=>s.id===task?.sheetId),client=role==='client',readOnly=client&&!!task?.version;
 const media=Array.from(new Map(comments.flatMap(c=>c.attachments||[]).map(a=>[a.id,a])).values()),shown=comments.filter(c=>job==='all'||(c.authorRole||'architect')===job).slice().sort((a,b)=>sort==='role'?(a.authorRole||'architect').localeCompare(b.authorRole||'architect')||a.created.localeCompare(b.created):a.created.localeCompare(b.created));
 function addFiles(incoming:File[]){const available=8-files.length;if(incoming.some(f=>f.size>25*1024*1024)){toast.error('Each attachment must be smaller than 25 MB.');return}if(incoming.length>available)toast('You can attach up to 8 files per message.');setFiles(old=>[...old,...incoming.slice(0,available)])}
 async function save(e:React.FormEvent){e.preventDefault();if(!task)return;setBusy(true);try{const saved=await onSave({...task,title:task.title.trim()});onTaskChange(saved);toast.success(task.version?'Task updated':'Task created')}catch{}finally{setBusy(false)}}
 async function send(e?:React.FormEvent){e?.preventDefault();if(!task?.version||busy||(!text.trim()&&!files.length))return;setBusy(true);try{
  const attachments:Attachment[]=[];
  for(let i=0;i<files.length;i++){const file=files[i];setProgress('Uploading '+(i+1)+' of '+files.length);let attachment=uploaded.current.get(file);if(!attachment){const form=new FormData();form.append('file',file);attachment=(await request('/api/attachments?project='+projectId+'&task='+task.id,{method:'POST',body:form})).attachment as Attachment;uploaded.current.set(file,attachment)}attachments.push(attachment)}
  setProgress('Sending');await onComment({id:uid(),type:'comment',sheetId:task.sheetId,taskId:task.id,text:text.trim(),attachments,author:name,created:new Date().toISOString(),visibility:task.visibility,audience:client?[]:messageAudience});setText('');setFiles([]);uploaded.current.clear();setPanel('chat');
 }catch(e:any){toast.error(e.message)}finally{setProgress('');setBusy(false)}}
 async function download(file:Attachment){try{const r=await fetch('/api/attachments?project='+projectId+'&id='+file.id+'&download=1',{headers});if(!r.ok)throw new Error('This attachment could not be downloaded.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e:any){toast.error(e.message)}}
 function attachment(file:Attachment){return <button key={file.id} className={'attachment-card '+(file.mime.startsWith('image/')?'photo':'file')} onClick={()=>file.mime.startsWith('image/')?setActiveFile(file):download(file)} type="button">{file.mime.startsWith('image/')?<AttachmentImage file={file} projectId={projectId} headers={headers}/>:<FileText size={27}/>}<span><strong>{file.name}</strong><small>{fileSize(file.size)}</small></span></button>}
 return <><Dialog open={open} onOpenChange={v=>!busy&&onOpenChange(v)}><DialogContent className="task-dialog" onInteractOutside={e=>{if(text.trim()||files.length||busy)e.preventDefault()}}><DialogHeader className="task-modal-header"><DialogDescription>{task?.version?'TASK #'+String(task.number).padStart(2,'0'):'NEW TASK'}{sheet?' · '+sheet.code:''}</DialogDescription><DialogTitle>{task?.version?task.title:'What needs to change?'}</DialogTitle></DialogHeader>
 {task&&<div className="mobile-task-tabs"><button className={panel==='details'?'active':''} onClick={()=>setPanel('details')}><FileText size={15}/> Details</button><button className={panel==='chat'?'active':''} onClick={()=>setPanel('chat')}>Conversation <span>{comments.length}</span></button><button className={panel==='media'?'active':''} onClick={()=>setPanel('media')}><Paperclip size={15}/> Files <span>{media.length}</span></button></div>}
 {task&&<div className={'task-modal-columns panel-'+panel} ref={modalBody}><section className="task-information"><div className="task-plan-context">{sheet&&<PlanPreview sheet={sheet} projectId={projectId} headers={headers} pin={task.position} number={task.number} focus={focus}/>}<div className="task-plan-caption"><span><MapPin size={14}/>{sheet?.code} · {task.position?'Pinned location':'No pin yet'}</span>{task.position&&<button type="button" className="icon-button" aria-label={focus?'Show full plan':'Zoom to task pin'} onClick={()=>setFocus(v=>!v)}>{focus?<ZoomOut size={16}/>:<ZoomIn size={16}/>}</button>}<button type="button" onClick={()=>onOpenPlan(task.sheetId)}>Open plan <ArrowUpRight size={14}/></button></div></div>
 <form className="form-stack task-fields" onSubmit={save}><label>Task title<input autoFocus={!task.version} aria-label="Task title" required maxLength={200} value={task.title} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,title:e.target.value})} placeholder="Describe one thing to change"/></label><label>Notes<textarea aria-label="Task notes" rows={3} value={task.description} maxLength={10000} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,description:e.target.value})} placeholder="Add context, dimensions or a question"/></label>
 <div className="form-grid"><label>Status<Choice label="Task status" value={task.status} disabled={client||busy} onChange={v=>onTaskChange({...task,status:v as Task['status']})} options={Object.entries(statusNames).map(([value,label])=>({value,label}))}/></label><label>Priority<Choice label="Task priority" value={task.priority} disabled={readOnly||busy} onChange={v=>onTaskChange({...task,priority:v as Task['priority']})} options={['low','medium','high'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))}/></label><label>Assigned to<input list="task-people" aria-label="Task assignee" value={task.assignee} disabled={client||busy} onChange={e=>onTaskChange({...task,assignee:e.target.value})}/><datalist id="task-people">{members.map(m=><option key={m.id} value={m.name}/>)}</datalist></label><label>Due date<input type="date" aria-label="Task due date" value={task.due} disabled={readOnly||busy} onChange={e=>onTaskChange({...task,due:e.target.value})}/></label></div>
 {!client&&<><div className="form-grid"><label>Shared with<Choice label="Task visibility" value={task.visibility} onChange={v=>onTaskChange({...task,visibility:v as Task['visibility']})} disabled={busy} options={[{value:'internal',label:'Internal team'},{value:'client',label:'Team and clients'}]}/></label><label>Visible roles<AudienceSelect label="Task visible roles" value={task.audience} onChange={audience=>onTaskChange({...task,audience})} disabled={busy}/></label></div><label>Review source<Choice label="Task review source" value={task.source} onChange={v=>onTaskChange({...task,source:v as Task['source']})} disabled={busy} options={['Internal review','Client review','Site visit'].map(value=>({value,label:value}))}/></label></>}
 {!readOnly&&<div className="task-form-buttons"><button className="button outline" type="button" disabled={busy} onClick={()=>onLocate(task)}><MapPin size={15}/>{task.position?'Move pin':'Place pin'}</button><button className="button primary" disabled={busy||!task.title.trim()}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {task.version?'Save changes':'Create task'}</button></div>}{task.version&&!client&&<button type="button" className="delete-task" disabled={busy} onClick={()=>onDelete(task)}><Trash2 size={14}/> Delete task</button>}
 </form></section>
 <section className="task-conversation" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(task.version&&!busy)addFiles(Array.from(e.dataTransfer.files))}}><div className="conversation-header"><Tabs value={panel==='media'?'media':'chat'} onValueChange={setPanel}><TabsList variant="line"><TabsTrigger value="chat">Conversation <span>{comments.length}</span></TabsTrigger><TabsTrigger value="media"><Paperclip size={15}/> Attachments <span>{media.length}</span></TabsTrigger></TabsList></Tabs></div>
 {panel!=='media'?<><div className="conversation-filters"><Choice label="Filter conversation by role" value={job} onChange={setJob} options={[{value:'all',label:'All roles'},...professionOptions]}/><Choice label="Sort conversation" value={sort} onChange={setSort} options={[{value:'time',label:'By time'},{value:'role',label:'By role'}]}/></div><div className="chat-messages" ref={chatScroll} aria-live="polite">{shown.map(c=><article key={c.id} className={'chat-message '+(c.creatorId===userId?'own':'')}><div className="chat-author"><strong>{c.author}</strong><span>{professionNames[c.authorRole||'architect']}</span>{!!c.audience?.length&&<span className="message-audience">{c.audience.map(p=>professionNames[p]).join(', ')} only</span>}</div><div className="chat-bubble">{c.attachments?.length?<div className="message-attachments">{c.attachments.map(attachment)}</div>:null}{c.text&&<p>{c.text}</p>}<time title={new Date(c.created).toLocaleString()}>{new Date(c.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · {new Date(c.created).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</time></div></article>)}{!shown.length&&<div className="conversation-empty"><span><Paperclip size={23}/></span><h3>{task.version?'Start the conversation':'Create the task first'}</h3><p>{task.version?'Add a message, a site photo or a file.':'Then add messages and photos here.'}</p></div>}</div></>:<div className="task-attachment-gallery"><div className="gallery-summary"><ImageIcon size={16}/>{media.filter(f=>f.mime.startsWith('image/')).length} photos · {media.filter(f=>!f.mime.startsWith('image/')).length} files</div><div className="attachment-grid">{media.map(attachment)}</div>{!media.length&&<div className="conversation-empty"><Paperclip size={25}/><p>Photos and files from this conversation appear here.</p></div>}</div>}
 <form className="chat-composer" onSubmit={send}>{files.length>0&&<div className="pending-attachments">{files.map((file,i)=><div key={i}><Paperclip size={13}/><span>{file.name}</span><button type="button" disabled={busy} aria-label={'Remove '+file.name} onClick={()=>setFiles(items=>items.filter((_,index)=>index!==i))}><X size={14}/></button></div>)}</div>}<textarea aria-label="Message" placeholder={task.version?'Write a message…':'Create the task to add messages'} rows={2} value={text} maxLength={10000} disabled={!task.version||busy} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} onPaste={e=>{const pasted=Array.from(e.clipboardData.files);if(pasted.length){e.preventDefault();addFiles(pasted)}}}/><div className="composer-actions"><input ref={uploadInput} type="file" hidden multiple onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value=''}}/><input ref={cameraInput} type="file" hidden accept="image/*" capture="environment" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value=''}}/><button type="button" className="icon-button" aria-label="Attach photos or files" disabled={!task.version||busy} onClick={()=>uploadInput.current?.click()}><Paperclip size={19}/></button><button type="button" className="icon-button" aria-label="Take a site photo" disabled={!task.version||busy} onClick={()=>cameraInput.current?.click()}><Camera size={19}/></button>{!client&&<AudienceSelect label="Message visible roles" value={messageAudience} onChange={setMessageAudience} disabled={busy}/>}<button className="send-message" aria-label="Send message" disabled={!task.version||busy||(!text.trim()&&!files.length)}>{busy?<LoaderCircle className="spin" size={19}/>:<Send size={19}/>}</button></div>{progress&&<span className="upload-progress" role="status">{progress}</span>}</form>
 </section></div>}
 </DialogContent></Dialog><Dialog open={!!activeFile} onOpenChange={v=>!v&&setActiveFile(null)}><DialogContent className="attachment-lightbox"><DialogHeader><DialogTitle>{activeFile?.name}</DialogTitle><DialogDescription>{activeFile?fileSize(activeFile.size):''}</DialogDescription></DialogHeader>{activeFile&&<><AttachmentImage file={activeFile} projectId={projectId} headers={headers} large/><button className="button outline" onClick={()=>download(activeFile)}><Download size={16}/> Download</button></>}</DialogContent></Dialog></>
}
