import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),owner:text('owner').notNull(),ownerProfession:text('owner_profession').notNull().default('architect'),name:text('name').notNull(),created:text('created').notNull(),nextTask:integer('next_task').notNull().default(1)},t=>[index('idx_projects_owner').on(t.owner)]);
export const records=sqliteTable('records',{id:text('id').notNull(),projectId:text('project_id').notNull(),type:text('type').notNull(),sheetId:text('sheet_id'),data:text('data').notNull(),creator:text('creator').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull()},t=>[primaryKey({columns:[t.projectId,t.id]}),index('idx_records_project_sheet').on(t.projectId,t.sheetId)]);
export const shares=sqliteTable('shares',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),tokenHash:text('token_hash').notNull(),role:text('role').notNull(),profession:text('profession').notNull().default('owner'),sheetIds:text('sheet_ids').notNull(),label:text('label').notNull(),created:text('created').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[index('idx_shares_token').on(t.tokenHash),index('idx_shares_project').on(t.projectId)]);
export const files=sqliteTable('files',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),name:text('name').notNull(),pageCount:integer('page_count').notNull().default(1),created:text('created').notNull()},t=>[index('idx_files_project').on(t.projectId)]);

export const guestSessions=sqliteTable('guest_sessions',{tokenHash:text('token_hash').primaryKey(),ownerId:text('owner_id').notNull(),expires:integer('expires').notNull()});
export const planFolders=sqliteTable('plan_folders',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),name:text('name').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull()},t=>[uniqueIndex('idx_plan_folders_project_name').on(t.projectId,t.name)]);
export const projectMembers=sqliteTable('project_members',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),userId:text('user_id'),email:text('email').notNull(),name:text('name').notNull(),profession:text('profession').notNull(),access:text('access').notNull(),created:text('created').notNull()},t=>[uniqueIndex('idx_members_project_email').on(t.projectId,t.email),index('idx_members_user').on(t.userId),index('idx_members_email').on(t.email)]);
export const attachments=sqliteTable('attachments',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),taskId:text('task_id').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),creator:text('creator').notNull(),created:text('created').notNull()},t=>[index('idx_attachments_project_task').on(t.projectId,t.taskId)]);
export const projectDocuments=sqliteTable('project_documents',{id:text('id').primaryKey(),projectId:text('project_id').notNull(),kind:text('kind').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),creator:text('creator').notNull(),author:text('author').notNull(),authorRole:text('author_role').notNull(),created:text('created').notNull()},t=>[index('idx_documents_project_kind').on(t.projectId,t.kind)]);
export const photoLikes=sqliteTable('photo_likes',{projectId:text('project_id').notNull(),photoId:text('photo_id').notNull(),userId:text('user_id').notNull(),created:text('created').notNull()},t=>[primaryKey({columns:[t.projectId,t.photoId,t.userId]}),index('idx_photo_likes_user').on(t.projectId,t.userId)]);
